//HintName: Mediator.g.cs
// <auto-generated>
//     Generated by the Mediator source generator.
// </auto-generated>

#pragma warning disable CS8019 // Unused usings
#pragma warning disable CS8321 // Unused local function
#pragma warning disable CS1998 // Async method lacks 'await' operators and will run synchronously

#nullable enable

using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.DependencyInjection.Extensions;
using System.Linq;

namespace Microsoft.Extensions.DependencyInjection
{
    /// <summary>
    /// DI extensions for Mediator.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Mediator.SourceGenerator", "3.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.Diagnostics.DebuggerStepThroughAttribute]
    public static class MediatorDependencyInjectionExtensions
    {
        /// <summary>
        /// Adds the Mediator implementation and handlers of your application.
        /// </summary>
        public static IServiceCollection AddMediator(this IServiceCollection services)
        {
            return AddMediator(services, null);
        }

        /// <summary>
        /// Adds the Mediator implementation and handlers of your application, with specified options.
        /// </summary>
        public static IServiceCollection AddMediator(this IServiceCollection services, global::System.Action<global::Mediator.MediatorOptions>? options)
        {
            var opts = new global::Mediator.MediatorOptions();
            if (options != null)
                options(opts);

            var configuredViaAttribute = true;
            if (opts.ServiceLifetime != global::Microsoft.Extensions.DependencyInjection.ServiceLifetime.Transient && !configuredViaAttribute)
            {
                var errMsg = "Invalid configuration detected for Mediator. ";
                errMsg += "Generated code for 'Transient' lifetime, but got '" + opts.ServiceLifetime + "' lifetime from options. ";
                errMsg += "This means that the source generator hasn't seen the 'AddMediator' method call during compilation. ";
                errMsg += "Make sure that the 'AddMediator' method is called from the project that references the Mediator.SourceGenerator package.";
                throw new global::System.Exception(errMsg);
            }

            services.Add(new global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor(typeof(global::Mediator2.Mediator), typeof(global::Mediator2.Mediator), global::Microsoft.Extensions.DependencyInjection.ServiceLifetime.Transient));
            services.TryAdd(new global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor(typeof(global::Mediator.IMediator), typeof(global::Mediator2.Mediator), global::Microsoft.Extensions.DependencyInjection.ServiceLifetime.Transient));
            services.TryAdd(new global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor(typeof(global::Mediator.ISender), typeof(global::Mediator2.Mediator), global::Microsoft.Extensions.DependencyInjection.ServiceLifetime.Transient));
            services.TryAdd(new global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor(typeof(global::Mediator.IPublisher), typeof(global::Mediator2.Mediator), global::Microsoft.Extensions.DependencyInjection.ServiceLifetime.Transient));

            // Register the notification publisher that was configured
            services.Add(new global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor(typeof(global::Mediator.ForeachAwaitPublisher), typeof(global::Mediator.ForeachAwaitPublisher), global::Microsoft.Extensions.DependencyInjection.ServiceLifetime.Transient));
            services.TryAdd(new global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor(typeof(global::Mediator.INotificationPublisher), sp => sp.GetRequiredService<global::Mediator.ForeachAwaitPublisher>(), global::Microsoft.Extensions.DependencyInjection.ServiceLifetime.Transient));

            // Register internal components
            services.Add(new global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor(typeof(global::Mediator2.Internals.IContainerProbe), typeof(global::Mediator2.Internals.ContainerProbe0), global::Microsoft.Extensions.DependencyInjection.ServiceLifetime.Transient));
            services.Add(new global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor(typeof(global::Mediator2.Internals.IContainerProbe), typeof(global::Mediator2.Internals.ContainerProbe1), global::Microsoft.Extensions.DependencyInjection.ServiceLifetime.Transient));
            services.Add(new global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor(typeof(global::Mediator2.Internals.ContainerMetadata), typeof(global::Mediator2.Internals.ContainerMetadata), global::Microsoft.Extensions.DependencyInjection.ServiceLifetime.Singleton));

            return services;

        }
    }
}

namespace Mediator2.Internals
{
    [global::System.CodeDom.Compiler.GeneratedCode("Mediator.SourceGenerator", "3.1.0.0")]
    internal interface IMessageHandlerBase
    {
        global::System.Threading.Tasks.ValueTask<object?> Handle(
            global::Mediator2.Mediator mediator,
            object request,
            global::System.Threading.CancellationToken cancellationToken
        );
    }
    [global::System.CodeDom.Compiler.GeneratedCode("Mediator.SourceGenerator", "3.1.0.0")]
    internal interface INotificationHandlerBase
    {
        global::System.Threading.Tasks.ValueTask Handle(
            global::Mediator2.Mediator mediator,
            object notification,
            global::System.Threading.CancellationToken cancellationToken
        );
    }
    [global::System.CodeDom.Compiler.GeneratedCode("Mediator.SourceGenerator", "3.1.0.0")]
    internal interface IStreamMessageHandlerBase
    {
        global::System.Collections.Generic.IAsyncEnumerable<object?> Handle(
            global::Mediator2.Mediator mediator,
            object request,
            global::System.Threading.CancellationToken cancellationToken
        );
    }

    [global::System.CodeDom.Compiler.GeneratedCode("Mediator.SourceGenerator", "3.1.0.0")]
    internal interface IRequestHandlerBase<TResponse> : IMessageHandlerBase
    {
        global::System.Threading.Tasks.ValueTask<TResponse> Handle(
            global::Mediator2.Mediator mediator,
            global::Mediator.IRequest<TResponse> request,
            global::System.Threading.CancellationToken cancellationToken
        );
    }
    [global::System.CodeDom.Compiler.GeneratedCode("Mediator.SourceGenerator", "3.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.Diagnostics.DebuggerStepThroughAttribute]
    internal sealed class RequestHandlerWrapper<TRequest, TResponse> : IRequestHandlerBase<TResponse>
        where TRequest : global::Mediator.IRequest<TResponse>
    {

        public global::System.Threading.Tasks.ValueTask<TResponse> Handle(
            global::Mediator2.Mediator mediator,
            TRequest request,
            global::System.Threading.CancellationToken cancellationToken
        )
        {
            var concreteHandler = mediator.Services.GetRequiredService<global::Mediator.IRequestHandler<TRequest, TResponse>>();
            var pipelineBehaviours = mediator.Services.GetServices<global::Mediator.IPipelineBehavior<TRequest, TResponse>>();
            var handler = (global::Mediator.MessageHandlerDelegate<TRequest, TResponse>)concreteHandler.Handle;

            global::Mediator.IPipelineBehavior<TRequest, TResponse>[] pipelineBehavioursArray;
            if (mediator.ServicesUnderlyingTypeIsArray)
            {
                global::System.Diagnostics.Debug.Assert(
                    pipelineBehaviours is global::Mediator.IPipelineBehavior<TRequest, TResponse>[]
                );
                pipelineBehavioursArray = global::System.Runtime.CompilerServices.Unsafe.As<global::Mediator.IPipelineBehavior<TRequest, TResponse>[]>(
                    pipelineBehaviours
                );
                for (int i = pipelineBehavioursArray.Length - 1; i >= 0; i--)
                {
                    var pipeline = pipelineBehavioursArray[i];
                    var handlerCopy = handler;
                    var pipelineCopy = pipeline;
                    handler = (TRequest message, System.Threading.CancellationToken cancellationToken) => pipelineCopy.Handle(message, handlerCopy, cancellationToken);
                }
            }
            else
            {
                global::System.Diagnostics.Debug.Assert(
                    pipelineBehaviours is not global::Mediator.IPipelineBehavior<TRequest, TResponse>[]
                );
                foreach (var pipeline in pipelineBehaviours.Reverse())
                {
                    var handlerCopy = handler;
                    var pipelineCopy = pipeline;
                    handler = (TRequest message, System.Threading.CancellationToken cancellationToken) => pipelineCopy.Handle(message, handlerCopy, cancellationToken);
                }
            }
            return handler(request, cancellationToken);
        }

        public global::System.Threading.Tasks.ValueTask<TResponse> Handle(
            global::Mediator2.Mediator mediator,
            global::Mediator.IRequest<TResponse> request,
            global::System.Threading.CancellationToken cancellationToken
        )
        {
            return Handle(mediator, (TRequest)request, cancellationToken);
        }

        public async global::System.Threading.Tasks.ValueTask<object?> Handle(
            global::Mediator2.Mediator mediator,
            object request,
            global::System.Threading.CancellationToken cancellationToken
        )
        {
            return await Handle(mediator, (TRequest)request, cancellationToken);
        }
    }
    [global::System.CodeDom.Compiler.GeneratedCode("Mediator.SourceGenerator", "3.1.0.0")]
    internal interface IStreamRequestHandlerBase<TResponse> : IStreamMessageHandlerBase
    {
        global::System.Collections.Generic.IAsyncEnumerable<TResponse> Handle(
            global::Mediator2.Mediator mediator,
            global::Mediator.IStreamRequest<TResponse> request,
            global::System.Threading.CancellationToken cancellationToken
        );
    }
    [global::System.CodeDom.Compiler.GeneratedCode("Mediator.SourceGenerator", "3.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.Diagnostics.DebuggerStepThroughAttribute]
    internal sealed class StreamRequestHandlerWrapper<TRequest, TResponse> : IStreamRequestHandlerBase<TResponse>
        where TRequest : global::Mediator.IStreamRequest<TResponse>
    {

        public global::System.Collections.Generic.IAsyncEnumerable<TResponse> Handle(
            global::Mediator2.Mediator mediator,
            TRequest request,
            global::System.Threading.CancellationToken cancellationToken
        )
        {
            var concreteHandler = mediator.Services.GetRequiredService<global::Mediator.IStreamRequestHandler<TRequest, TResponse>>();
            var pipelineBehaviours = mediator.Services.GetServices<global::Mediator.IStreamPipelineBehavior<TRequest, TResponse>>();
            var handler = (global::Mediator.StreamHandlerDelegate<TRequest, TResponse>)concreteHandler.Handle;

            global::Mediator.IStreamPipelineBehavior<TRequest, TResponse>[] pipelineBehavioursArray;
            if (mediator.ServicesUnderlyingTypeIsArray)
            {
                global::System.Diagnostics.Debug.Assert(
                    pipelineBehaviours is global::Mediator.IStreamPipelineBehavior<TRequest, TResponse>[]
                );
                pipelineBehavioursArray = global::System.Runtime.CompilerServices.Unsafe.As<global::Mediator.IStreamPipelineBehavior<TRequest, TResponse>[]>(
                    pipelineBehaviours
                );
                for (int i = pipelineBehavioursArray.Length - 1; i >= 0; i--)
                {
                    var pipeline = pipelineBehavioursArray[i];
                    var handlerCopy = handler;
                    var pipelineCopy = pipeline;
                    handler = (TRequest message, System.Threading.CancellationToken cancellationToken) => pipelineCopy.Handle(message, handlerCopy, cancellationToken);
                }
            }
            else
            {
                global::System.Diagnostics.Debug.Assert(
                    pipelineBehaviours is not global::Mediator.IStreamPipelineBehavior<TRequest, TResponse>[]
                );
                foreach (var pipeline in pipelineBehaviours.Reverse())
                {
                    var handlerCopy = handler;
                    var pipelineCopy = pipeline;
                    handler = (TRequest message, System.Threading.CancellationToken cancellationToken) => pipelineCopy.Handle(message, handlerCopy, cancellationToken);
                }
            }
            return handler(request, cancellationToken);
        }

        public global::System.Collections.Generic.IAsyncEnumerable<TResponse> Handle(
            global::Mediator2.Mediator mediator,
            global::Mediator.IStreamRequest<TResponse> request,
            global::System.Threading.CancellationToken cancellationToken
        )
        {
            return Handle(mediator, (TRequest)request, cancellationToken);
        }

        public async global::System.Collections.Generic.IAsyncEnumerable<object?> Handle(
            global::Mediator2.Mediator mediator,
            object request,
            [global::System.Runtime.CompilerServices.EnumeratorCancellation] global::System.Threading.CancellationToken cancellationToken
        )
        {
            await foreach (var el in Handle(mediator, (TRequest)request, cancellationToken))
                yield return el;
        }
    }
    [global::System.CodeDom.Compiler.GeneratedCode("Mediator.SourceGenerator", "3.1.0.0")]
    internal interface ICommandHandlerBase<TResponse> : IMessageHandlerBase
    {
        global::System.Threading.Tasks.ValueTask<TResponse> Handle(
            global::Mediator2.Mediator mediator,
            global::Mediator.ICommand<TResponse> request,
            global::System.Threading.CancellationToken cancellationToken
        );
    }
    [global::System.CodeDom.Compiler.GeneratedCode("Mediator.SourceGenerator", "3.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.Diagnostics.DebuggerStepThroughAttribute]
    internal sealed class CommandHandlerWrapper<TRequest, TResponse> : ICommandHandlerBase<TResponse>
        where TRequest : global::Mediator.ICommand<TResponse>
    {

        public global::System.Threading.Tasks.ValueTask<TResponse> Handle(
            global::Mediator2.Mediator mediator,
            TRequest request,
            global::System.Threading.CancellationToken cancellationToken
        )
        {
            var concreteHandler = mediator.Services.GetRequiredService<global::Mediator.ICommandHandler<TRequest, TResponse>>();
            var pipelineBehaviours = mediator.Services.GetServices<global::Mediator.IPipelineBehavior<TRequest, TResponse>>();
            var handler = (global::Mediator.MessageHandlerDelegate<TRequest, TResponse>)concreteHandler.Handle;

            global::Mediator.IPipelineBehavior<TRequest, TResponse>[] pipelineBehavioursArray;
            if (mediator.ServicesUnderlyingTypeIsArray)
            {
                global::System.Diagnostics.Debug.Assert(
                    pipelineBehaviours is global::Mediator.IPipelineBehavior<TRequest, TResponse>[]
                );
                pipelineBehavioursArray = global::System.Runtime.CompilerServices.Unsafe.As<global::Mediator.IPipelineBehavior<TRequest, TResponse>[]>(
                    pipelineBehaviours
                );
                for (int i = pipelineBehavioursArray.Length - 1; i >= 0; i--)
                {
                    var pipeline = pipelineBehavioursArray[i];
                    var handlerCopy = handler;
                    var pipelineCopy = pipeline;
                    handler = (TRequest message, System.Threading.CancellationToken cancellationToken) => pipelineCopy.Handle(message, handlerCopy, cancellationToken);
                }
            }
            else
            {
                global::System.Diagnostics.Debug.Assert(
                    pipelineBehaviours is not global::Mediator.IPipelineBehavior<TRequest, TResponse>[]
                );
                foreach (var pipeline in pipelineBehaviours.Reverse())
                {
                    var handlerCopy = handler;
                    var pipelineCopy = pipeline;
                    handler = (TRequest message, System.Threading.CancellationToken cancellationToken) => pipelineCopy.Handle(message, handlerCopy, cancellationToken);
                }
            }
            return handler(request, cancellationToken);
        }

        public global::System.Threading.Tasks.ValueTask<TResponse> Handle(
            global::Mediator2.Mediator mediator,
            global::Mediator.ICommand<TResponse> request,
            global::System.Threading.CancellationToken cancellationToken
        )
        {
            return Handle(mediator, (TRequest)request, cancellationToken);
        }

        public async global::System.Threading.Tasks.ValueTask<object?> Handle(
            global::Mediator2.Mediator mediator,
            object request,
            global::System.Threading.CancellationToken cancellationToken
        )
        {
            return await Handle(mediator, (TRequest)request, cancellationToken);
        }
    }
    [global::System.CodeDom.Compiler.GeneratedCode("Mediator.SourceGenerator", "3.1.0.0")]
    internal interface IStreamCommandHandlerBase<TResponse> : IStreamMessageHandlerBase
    {
        global::System.Collections.Generic.IAsyncEnumerable<TResponse> Handle(
            global::Mediator2.Mediator mediator,
            global::Mediator.IStreamCommand<TResponse> request,
            global::System.Threading.CancellationToken cancellationToken
        );
    }
    [global::System.CodeDom.Compiler.GeneratedCode("Mediator.SourceGenerator", "3.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.Diagnostics.DebuggerStepThroughAttribute]
    internal sealed class StreamCommandHandlerWrapper<TRequest, TResponse> : IStreamCommandHandlerBase<TResponse>
        where TRequest : global::Mediator.IStreamCommand<TResponse>
    {

        public global::System.Collections.Generic.IAsyncEnumerable<TResponse> Handle(
            global::Mediator2.Mediator mediator,
            TRequest request,
            global::System.Threading.CancellationToken cancellationToken
        )
        {
            var concreteHandler = mediator.Services.GetRequiredService<global::Mediator.IStreamCommandHandler<TRequest, TResponse>>();
            var pipelineBehaviours = mediator.Services.GetServices<global::Mediator.IStreamPipelineBehavior<TRequest, TResponse>>();
            var handler = (global::Mediator.StreamHandlerDelegate<TRequest, TResponse>)concreteHandler.Handle;

            global::Mediator.IStreamPipelineBehavior<TRequest, TResponse>[] pipelineBehavioursArray;
            if (mediator.ServicesUnderlyingTypeIsArray)
            {
                global::System.Diagnostics.Debug.Assert(
                    pipelineBehaviours is global::Mediator.IStreamPipelineBehavior<TRequest, TResponse>[]
                );
                pipelineBehavioursArray = global::System.Runtime.CompilerServices.Unsafe.As<global::Mediator.IStreamPipelineBehavior<TRequest, TResponse>[]>(
                    pipelineBehaviours
                );
                for (int i = pipelineBehavioursArray.Length - 1; i >= 0; i--)
                {
                    var pipeline = pipelineBehavioursArray[i];
                    var handlerCopy = handler;
                    var pipelineCopy = pipeline;
                    handler = (TRequest message, System.Threading.CancellationToken cancellationToken) => pipelineCopy.Handle(message, handlerCopy, cancellationToken);
                }
            }
            else
            {
                global::System.Diagnostics.Debug.Assert(
                    pipelineBehaviours is not global::Mediator.IStreamPipelineBehavior<TRequest, TResponse>[]
                );
                foreach (var pipeline in pipelineBehaviours.Reverse())
                {
                    var handlerCopy = handler;
                    var pipelineCopy = pipeline;
                    handler = (TRequest message, System.Threading.CancellationToken cancellationToken) => pipelineCopy.Handle(message, handlerCopy, cancellationToken);
                }
            }
            return handler(request, cancellationToken);
        }

        public global::System.Collections.Generic.IAsyncEnumerable<TResponse> Handle(
            global::Mediator2.Mediator mediator,
            global::Mediator.IStreamCommand<TResponse> request,
            global::System.Threading.CancellationToken cancellationToken
        )
        {
            return Handle(mediator, (TRequest)request, cancellationToken);
        }

        public async global::System.Collections.Generic.IAsyncEnumerable<object?> Handle(
            global::Mediator2.Mediator mediator,
            object request,
            [global::System.Runtime.CompilerServices.EnumeratorCancellation] global::System.Threading.CancellationToken cancellationToken
        )
        {
            await foreach (var el in Handle(mediator, (TRequest)request, cancellationToken))
                yield return el;
        }
    }
    [global::System.CodeDom.Compiler.GeneratedCode("Mediator.SourceGenerator", "3.1.0.0")]
    internal interface IQueryHandlerBase<TResponse> : IMessageHandlerBase
    {
        global::System.Threading.Tasks.ValueTask<TResponse> Handle(
            global::Mediator2.Mediator mediator,
            global::Mediator.IQuery<TResponse> request,
            global::System.Threading.CancellationToken cancellationToken
        );
    }
    [global::System.CodeDom.Compiler.GeneratedCode("Mediator.SourceGenerator", "3.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.Diagnostics.DebuggerStepThroughAttribute]
    internal sealed class QueryHandlerWrapper<TRequest, TResponse> : IQueryHandlerBase<TResponse>
        where TRequest : global::Mediator.IQuery<TResponse>
    {

        public global::System.Threading.Tasks.ValueTask<TResponse> Handle(
            global::Mediator2.Mediator mediator,
            TRequest request,
            global::System.Threading.CancellationToken cancellationToken
        )
        {
            var concreteHandler = mediator.Services.GetRequiredService<global::Mediator.IQueryHandler<TRequest, TResponse>>();
            var pipelineBehaviours = mediator.Services.GetServices<global::Mediator.IPipelineBehavior<TRequest, TResponse>>();
            var handler = (global::Mediator.MessageHandlerDelegate<TRequest, TResponse>)concreteHandler.Handle;

            global::Mediator.IPipelineBehavior<TRequest, TResponse>[] pipelineBehavioursArray;
            if (mediator.ServicesUnderlyingTypeIsArray)
            {
                global::System.Diagnostics.Debug.Assert(
                    pipelineBehaviours is global::Mediator.IPipelineBehavior<TRequest, TResponse>[]
                );
                pipelineBehavioursArray = global::System.Runtime.CompilerServices.Unsafe.As<global::Mediator.IPipelineBehavior<TRequest, TResponse>[]>(
                    pipelineBehaviours
                );
                for (int i = pipelineBehavioursArray.Length - 1; i >= 0; i--)
                {
                    var pipeline = pipelineBehavioursArray[i];
                    var handlerCopy = handler;
                    var pipelineCopy = pipeline;
                    handler = (TRequest message, System.Threading.CancellationToken cancellationToken) => pipelineCopy.Handle(message, handlerCopy, cancellationToken);
                }
            }
            else
            {
                global::System.Diagnostics.Debug.Assert(
                    pipelineBehaviours is not global::Mediator.IPipelineBehavior<TRequest, TResponse>[]
                );
                foreach (var pipeline in pipelineBehaviours.Reverse())
                {
                    var handlerCopy = handler;
                    var pipelineCopy = pipeline;
                    handler = (TRequest message, System.Threading.CancellationToken cancellationToken) => pipelineCopy.Handle(message, handlerCopy, cancellationToken);
                }
            }
            return handler(request, cancellationToken);
        }

        public global::System.Threading.Tasks.ValueTask<TResponse> Handle(
            global::Mediator2.Mediator mediator,
            global::Mediator.IQuery<TResponse> request,
            global::System.Threading.CancellationToken cancellationToken
        )
        {
            return Handle(mediator, (TRequest)request, cancellationToken);
        }

        public async global::System.Threading.Tasks.ValueTask<object?> Handle(
            global::Mediator2.Mediator mediator,
            object request,
            global::System.Threading.CancellationToken cancellationToken
        )
        {
            return await Handle(mediator, (TRequest)request, cancellationToken);
        }
    }
    [global::System.CodeDom.Compiler.GeneratedCode("Mediator.SourceGenerator", "3.1.0.0")]
    internal interface IStreamQueryHandlerBase<TResponse> : IStreamMessageHandlerBase
    {
        global::System.Collections.Generic.IAsyncEnumerable<TResponse> Handle(
            global::Mediator2.Mediator mediator,
            global::Mediator.IStreamQuery<TResponse> request,
            global::System.Threading.CancellationToken cancellationToken
        );
    }
    [global::System.CodeDom.Compiler.GeneratedCode("Mediator.SourceGenerator", "3.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.Diagnostics.DebuggerStepThroughAttribute]
    internal sealed class StreamQueryHandlerWrapper<TRequest, TResponse> : IStreamQueryHandlerBase<TResponse>
        where TRequest : global::Mediator.IStreamQuery<TResponse>
    {

        public global::System.Collections.Generic.IAsyncEnumerable<TResponse> Handle(
            global::Mediator2.Mediator mediator,
            TRequest request,
            global::System.Threading.CancellationToken cancellationToken
        )
        {
            var concreteHandler = mediator.Services.GetRequiredService<global::Mediator.IStreamQueryHandler<TRequest, TResponse>>();
            var pipelineBehaviours = mediator.Services.GetServices<global::Mediator.IStreamPipelineBehavior<TRequest, TResponse>>();
            var handler = (global::Mediator.StreamHandlerDelegate<TRequest, TResponse>)concreteHandler.Handle;

            global::Mediator.IStreamPipelineBehavior<TRequest, TResponse>[] pipelineBehavioursArray;
            if (mediator.ServicesUnderlyingTypeIsArray)
            {
                global::System.Diagnostics.Debug.Assert(
                    pipelineBehaviours is global::Mediator.IStreamPipelineBehavior<TRequest, TResponse>[]
                );
                pipelineBehavioursArray = global::System.Runtime.CompilerServices.Unsafe.As<global::Mediator.IStreamPipelineBehavior<TRequest, TResponse>[]>(
                    pipelineBehaviours
                );
                for (int i = pipelineBehavioursArray.Length - 1; i >= 0; i--)
                {
                    var pipeline = pipelineBehavioursArray[i];
                    var handlerCopy = handler;
                    var pipelineCopy = pipeline;
                    handler = (TRequest message, System.Threading.CancellationToken cancellationToken) => pipelineCopy.Handle(message, handlerCopy, cancellationToken);
                }
            }
            else
            {
                global::System.Diagnostics.Debug.Assert(
                    pipelineBehaviours is not global::Mediator.IStreamPipelineBehavior<TRequest, TResponse>[]
                );
                foreach (var pipeline in pipelineBehaviours.Reverse())
                {
                    var handlerCopy = handler;
                    var pipelineCopy = pipeline;
                    handler = (TRequest message, System.Threading.CancellationToken cancellationToken) => pipelineCopy.Handle(message, handlerCopy, cancellationToken);
                }
            }
            return handler(request, cancellationToken);
        }

        public global::System.Collections.Generic.IAsyncEnumerable<TResponse> Handle(
            global::Mediator2.Mediator mediator,
            global::Mediator.IStreamQuery<TResponse> request,
            global::System.Threading.CancellationToken cancellationToken
        )
        {
            return Handle(mediator, (TRequest)request, cancellationToken);
        }

        public async global::System.Collections.Generic.IAsyncEnumerable<object?> Handle(
            global::Mediator2.Mediator mediator,
            object request,
            [global::System.Runtime.CompilerServices.EnumeratorCancellation] global::System.Threading.CancellationToken cancellationToken
        )
        {
            await foreach (var el in Handle(mediator, (TRequest)request, cancellationToken))
                yield return el;
        }
    }

    [global::System.CodeDom.Compiler.GeneratedCode("Mediator.SourceGenerator", "3.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.Diagnostics.DebuggerStepThroughAttribute]
    internal sealed class NotificationHandlerWrapper<TNotification> : INotificationHandlerBase
        where TNotification : global::Mediator.INotification
    {

        public global::System.Threading.Tasks.ValueTask Handle(
            global::Mediator2.Mediator mediator,
            TNotification notification,
            global::System.Threading.CancellationToken cancellationToken
        )
        {
            var handlers = mediator.Services.GetServices<global::Mediator.INotificationHandler<TNotification>>();
            var isArray = mediator.ServicesUnderlyingTypeIsArray;
            if (isArray)
            {
                global::System.Diagnostics.Debug.Assert(
                    handlers is global::Mediator.INotificationHandler<TNotification>[],
                    $"Unexpected type: {handlers.GetType()}"
                );
                if (global::System.Runtime.CompilerServices.Unsafe.As<global::Mediator.INotificationHandler<TNotification>[]>(handlers).Length == 0)
                {
                    return default;
                }
            }
            else
            {
                global::System.Diagnostics.Debug.Assert(
                    handlers is not global::Mediator.INotificationHandler<TNotification>[],
                    $"Unexpected type: {handlers.GetType()}"
                );
            }
            return mediator.NotificationPublisher.Publish(
                new global::Mediator.NotificationHandlers<TNotification>(handlers, isArray),
                notification,
                cancellationToken
            );
        }

        public global::System.Threading.Tasks.ValueTask Handle(
            global::Mediator2.Mediator mediator,
            object notification,
            global::System.Threading.CancellationToken cancellationToken
        )
        {
            return Handle(mediator, (TNotification)notification, cancellationToken);
        }
    }

    internal interface IContainerProbe { }
    internal sealed class ContainerProbe0 : IContainerProbe { }
    internal sealed class ContainerProbe1 : IContainerProbe { }

    [global::System.CodeDom.Compiler.GeneratedCode("Mediator.SourceGenerator", "3.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.Diagnostics.DebuggerStepThroughAttribute]
    internal sealed class ContainerMetadata
    {
        public readonly bool ServicesUnderlyingTypeIsArray;

        public readonly global::System.Collections.Frozen.FrozenDictionary<global::System.Type, object> RequestHandlerWrappers;
        public readonly global::System.Collections.Frozen.FrozenDictionary<global::System.Type, object> CommandHandlerWrappers;
        public readonly global::System.Collections.Frozen.FrozenDictionary<global::System.Type, object> QueryHandlerWrappers;

        public readonly global::System.Collections.Frozen.FrozenDictionary<global::System.Type, object> StreamRequestHandlerWrappers;
        public readonly global::System.Collections.Frozen.FrozenDictionary<global::System.Type, object> StreamCommandHandlerWrappers;
        public readonly global::System.Collections.Frozen.FrozenDictionary<global::System.Type, object> StreamQueryHandlerWrappers;

        public readonly global::System.Collections.Frozen.FrozenDictionary<global::System.Type, object> NotificationHandlerWrappers;

        public ContainerMetadata(global::System.IServiceProvider sp)
        {
            ServicesUnderlyingTypeIsArray = sp.GetServices<global::Mediator2.Internals.IContainerProbe>() is global::Mediator2.Internals.IContainerProbe[];

            var requestHandlerTypes = new global::System.Collections.Generic.Dictionary<global::System.Type, object>(0);
            var commandHandlerTypes = new global::System.Collections.Generic.Dictionary<global::System.Type, object>(0);
            var queryHandlerTypes = new global::System.Collections.Generic.Dictionary<global::System.Type, object>(0);
            RequestHandlerWrappers = global::System.Collections.Frozen.FrozenDictionary.ToFrozenDictionary(requestHandlerTypes);
            CommandHandlerWrappers = global::System.Collections.Frozen.FrozenDictionary.ToFrozenDictionary(commandHandlerTypes);
            QueryHandlerWrappers = global::System.Collections.Frozen.FrozenDictionary.ToFrozenDictionary(queryHandlerTypes);

            var streamRequestHandlerTypes = new global::System.Collections.Generic.Dictionary<global::System.Type, object>(0);
            var streamCommandHandlerTypes = new global::System.Collections.Generic.Dictionary<global::System.Type, object>(0);
            var streamQueryHandlerTypes = new global::System.Collections.Generic.Dictionary<global::System.Type, object>(0);
            StreamRequestHandlerWrappers = global::System.Collections.Frozen.FrozenDictionary.ToFrozenDictionary(streamRequestHandlerTypes);
            StreamCommandHandlerWrappers = global::System.Collections.Frozen.FrozenDictionary.ToFrozenDictionary(streamCommandHandlerTypes);
            StreamQueryHandlerWrappers = global::System.Collections.Frozen.FrozenDictionary.ToFrozenDictionary(streamQueryHandlerTypes);

            var notificationHandlerTypes = new global::System.Collections.Generic.Dictionary<global::System.Type, object>(0);
            NotificationHandlerWrappers = global::System.Collections.Frozen.FrozenDictionary.ToFrozenDictionary(notificationHandlerTypes);
        }
    }
}

namespace Mediator2
{
    /// <summary>
    /// Generated code for Mediator implementation.
    /// This type is also registered as a DI service.
    /// Can be used directly for high performance scenarios.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Mediator.SourceGenerator", "3.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.Diagnostics.DebuggerStepThroughAttribute]
    public sealed partial class Mediator : global::Mediator.IMediator, global::Mediator.ISender, global::Mediator.IPublisher
    {
        internal readonly global::System.IServiceProvider Services;
        private global::Mediator.ForeachAwaitPublisher? _notificationPublisher;
        internal global::Mediator.ForeachAwaitPublisher NotificationPublisher
        {
            [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
            get
            {
                if (_notificationPublisher == null)
                    _notificationPublisher = Services.GetRequiredService<global::Mediator.ForeachAwaitPublisher>();
                return _notificationPublisher!;
            }
        }
        private global::Mediator2.Internals.ContainerMetadata? _containerMetadataStorage;
        private global::Mediator2.Internals.ContainerMetadata _containerMetadata
        {
            [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
            get
            {
                if (_containerMetadataStorage == null)
                {
                    var containerMetadata = Services.GetRequiredService<global::Mediator2.Internals.ContainerMetadata>();
                    _containerMetadataStorage = containerMetadata;
                    return containerMetadata;
                }
                return _containerMetadataStorage;
            }
        }
        internal bool ServicesUnderlyingTypeIsArray => _containerMetadata.ServicesUnderlyingTypeIsArray;

        /// <summary>
        /// The lifetime of Mediator-related service registrations in DI container.
        /// </summary>
        public const global::Microsoft.Extensions.DependencyInjection.ServiceLifetime ServiceLifetime = global::Microsoft.Extensions.DependencyInjection.ServiceLifetime.Transient;

        /// <summary>
        /// The caching mode configuration for Mediator handler resolution.
        /// </summary>
        public const global::Mediator.CachingMode CachingMode = global::Mediator.CachingMode.Eager;

        /// <summary>
        /// The name of the notification publisher service that was configured.
        /// </summary>
        public const string NotificationPublisherName = "ForeachAwaitPublisher";

        /// <summary>
        /// The total number of Mediator messages that were discovered.
        /// </summary>
        public const int TotalMessages = 0;

        /// <summary>
        /// Constructor for DI, should not be used by consumer.
        /// </summary>
        public Mediator(global::System.IServiceProvider sp)
        {
            Services = sp;
        }



        /// <summary>
        /// Send request.
        /// Throws <see cref="global::System.ArgumentNullException"/> if message is null.
        /// Throws <see cref="global::Mediator.InvalidMessageException"/> if request does not implement <see cref="global::Mediator.IRequest{TResponse}"/>.
        /// Throws <see cref="global::Mediator.MissingMessageHandlerException"/> if no handler is registered.
        /// </summary>
        /// <param name="request">Incoming request</param>
        /// <param name="cancellationToken">Cancellation token</param>
        /// <returns>Awaitable task</returns>
        public global::System.Threading.Tasks.ValueTask<TResponse> Send<TResponse>(
            global::Mediator.IRequest<TResponse> request,
            global::System.Threading.CancellationToken cancellationToken = default
        )
        {
            ThrowInvalidRequest(request, nameof(request));
            return default;
        }

        private async global::System.Threading.Tasks.ValueTask<TResponse> SendAsync<TResponse>(
            global::Mediator.IRequest<TResponse> request,
            global::System.Threading.CancellationToken cancellationToken = default
        )
        {
            ThrowInvalidRequest(request, nameof(request));
            return default!;
        }

        /// <summary>
        /// Create stream for request.
        /// Throws <see cref="global::System.ArgumentNullException"/> if message is null.
        /// Throws <see cref="global::Mediator.InvalidMessageException"/> if request does not implement <see cref="global::Mediator.IStreamRequest{TResponse}"/>.
        /// Throws <see cref="global::Mediator.MissingMessageHandlerException"/> if no handler is registered.
        /// </summary>
        /// <param name="request">Incoming message</param>
        /// <param name="cancellationToken">Cancellation token</param>
        /// <returns>Async enumerable</returns>
        public global::System.Collections.Generic.IAsyncEnumerable<TResponse> CreateStream<TResponse>(
            global::Mediator.IStreamRequest<TResponse> request,
            global::System.Threading.CancellationToken cancellationToken = default
        )
        {
            ThrowInvalidStreamRequest(request, nameof(request));
            return default!;
        }

        /// <summary>
        /// Send command.
        /// Throws <see cref="global::System.ArgumentNullException"/> if message is null.
        /// Throws <see cref="global::Mediator.InvalidMessageException"/> if command does not implement <see cref="global::Mediator.ICommand{TResponse}"/>.
        /// Throws <see cref="global::Mediator.MissingMessageHandlerException"/> if no handler is registered.
        /// </summary>
        /// <param name="command">Incoming command</param>
        /// <param name="cancellationToken">Cancellation token</param>
        /// <returns>Awaitable task</returns>
        public global::System.Threading.Tasks.ValueTask<TResponse> Send<TResponse>(
            global::Mediator.ICommand<TResponse> command,
            global::System.Threading.CancellationToken cancellationToken = default
        )
        {
            ThrowInvalidCommand(command, nameof(command));
            return default;
        }

        private async global::System.Threading.Tasks.ValueTask<TResponse> SendAsync<TResponse>(
            global::Mediator.ICommand<TResponse> command,
            global::System.Threading.CancellationToken cancellationToken = default
        )
        {
            ThrowInvalidCommand(command, nameof(command));
            return default!;
        }

        /// <summary>
        /// Create stream for command.
        /// Throws <see cref="global::System.ArgumentNullException"/> if message is null.
        /// Throws <see cref="global::Mediator.InvalidMessageException"/> if command does not implement <see cref="global::Mediator.IStreamCommand{TResponse}"/>.
        /// Throws <see cref="global::Mediator.MissingMessageHandlerException"/> if no handler is registered.
        /// </summary>
        /// <param name="command">Incoming message</param>
        /// <param name="cancellationToken">Cancellation token</param>
        /// <returns>Async enumerable</returns>
        public global::System.Collections.Generic.IAsyncEnumerable<TResponse> CreateStream<TResponse>(
            global::Mediator.IStreamCommand<TResponse> command,
            global::System.Threading.CancellationToken cancellationToken = default
        )
        {
            ThrowInvalidStreamCommand(command, nameof(command));
            return default!;
        }

        /// <summary>
        /// Send query.
        /// Throws <see cref="global::System.ArgumentNullException"/> if message is null.
        /// Throws <see cref="global::Mediator.InvalidMessageException"/> if query does not implement <see cref="global::Mediator.IQuery{TResponse}"/>.
        /// Throws <see cref="global::Mediator.MissingMessageHandlerException"/> if no handler is registered.
        /// </summary>
        /// <param name="query">Incoming query</param>
        /// <param name="cancellationToken">Cancellation token</param>
        /// <returns>Awaitable task</returns>
        public global::System.Threading.Tasks.ValueTask<TResponse> Send<TResponse>(
            global::Mediator.IQuery<TResponse> query,
            global::System.Threading.CancellationToken cancellationToken = default
        )
        {
            ThrowInvalidQuery(query, nameof(query));
            return default;
        }

        private async global::System.Threading.Tasks.ValueTask<TResponse> SendAsync<TResponse>(
            global::Mediator.IQuery<TResponse> query,
            global::System.Threading.CancellationToken cancellationToken = default
        )
        {
            ThrowInvalidQuery(query, nameof(query));
            return default!;
        }

        /// <summary>
        /// Create stream for query.
        /// Throws <see cref="global::System.ArgumentNullException"/> if message is null.
        /// Throws <see cref="global::Mediator.InvalidMessageException"/> if query does not implement <see cref="global::Mediator.IStreamQuery{TResponse}"/>.
        /// Throws <see cref="global::Mediator.MissingMessageHandlerException"/> if no handler is registered.
        /// </summary>
        /// <param name="query">Incoming message</param>
        /// <param name="cancellationToken">Cancellation token</param>
        /// <returns>Async enumerable</returns>
        public global::System.Collections.Generic.IAsyncEnumerable<TResponse> CreateStream<TResponse>(
            global::Mediator.IStreamQuery<TResponse> query,
            global::System.Threading.CancellationToken cancellationToken = default
        )
        {
            ThrowInvalidStreamQuery(query, nameof(query));
            return default!;
        }

        /// <summary>
        /// Send message.
        /// Throws <see cref="global::System.ArgumentNullException"/> if message is null.
        /// Throws <see cref="global::Mediator.InvalidMessageException"/> if message does not implement <see cref="global::Mediator.IMessage"/>.
        /// Throws <see cref="global::Mediator.MissingMessageHandlerException"/> if no handler is registered.
        /// </summary>
        /// <param name="message">Incoming message</param>
        /// <param name="cancellationToken">Cancellation token</param>
        /// <returns>Awaitable task</returns>
        public global::System.Threading.Tasks.ValueTask<object?> Send(
            object message,
            global::System.Threading.CancellationToken cancellationToken = default
        )
        {
            ThrowInvalidMessage(message, nameof(message));
            return default;
        }

        /// <summary>
        /// Create stream.
        /// Throws <see cref="global::System.ArgumentNullException"/> if message is null.
        /// Throws <see cref="global::Mediator.InvalidMessageException"/> if message does not implement <see cref="global::Mediator.IStreamMessage"/>.
        /// Throws <see cref="global::Mediator.MissingMessageHandlerException"/> if no handler is registered.
        /// </summary>
        /// <param name="message">Incoming message</param>
        /// <param name="cancellationToken">Cancellation token</param>
        /// <returns>Async enumerable</returns>
        public global::System.Collections.Generic.IAsyncEnumerable<object?> CreateStream(
            object message,
            global::System.Threading.CancellationToken cancellationToken = default
        )
        {
            ThrowInvalidStreamMessage(message, nameof(message));
            return default!;
        }

        /// <summary>
        /// Publish notification.
        /// Throws <see cref="global::System.ArgumentNullException"/> if message is null.
        /// Throws <see cref="global::Mediator.InvalidMessageException"/> if notification does not implement <see cref="global::Mediator.INotification"/>.
        /// Throws <see cref="global::System.AggregateException"/> if handlers throw exception(s).
        /// Drops messages
        /// </summary>
        /// <param name="notification">Incoming notification</param>
        /// <param name="cancellationToken">Cancellation token</param>
        /// <returns>Awaitable task</returns>
        public global::System.Threading.Tasks.ValueTask Publish(
            object notification,
            global::System.Threading.CancellationToken cancellationToken = default
        )
        {
            ThrowInvalidNotification(notification, nameof(notification));
            return default;
        }

        /// <summary>
        /// Publish notification.
        /// Throws <see cref="global::System.ArgumentNullException"/> if message is null.
        /// Throws <see cref="global::Mediator.InvalidMessageException"/> if notification does not implement <see cref="global::Mediator.INotification"/>.
        /// Throws <see cref="global::System.AggregateException"/> if handlers throw exception(s).
        /// </summary>
        /// <param name="notification">Incoming notification</param>
        /// <param name="cancellationToken">Cancellation token</param>
        /// <returns>Awaitable task</returns>
        public global::System.Threading.Tasks.ValueTask Publish<TNotification>(
            TNotification notification,
            global::System.Threading.CancellationToken cancellationToken = default
        )
            where TNotification : global::Mediator.INotification
        {
            ThrowInvalidNotification(notification, nameof(notification));
            return default;
        }

#if NETSTANDARD2_1_OR_GREATER
        [global::System.Diagnostics.CodeAnalysis.DoesNotReturn]
#endif
        private static void ThrowMissingHandler(object msg) =>
            throw new global::Mediator.MissingMessageHandlerException(msg);

#if NETSTANDARD2_1_OR_GREATER
        [global::System.Diagnostics.CodeAnalysis.DoesNotReturn]
#endif
        private static void ThrowInvalidMessage<T>(T? msg, string? paramName = null)
        {
            if (msg == null)
                ThrowArgumentNull(paramName);
            else if (!(msg is global::Mediator.IMessage))
                ThrowInvalidMessage(msg);
            else
                ThrowMissingHandler(msg);
        }

#if NETSTANDARD2_1_OR_GREATER
        [global::System.Diagnostics.CodeAnalysis.DoesNotReturn]
#endif
        private static void ThrowInvalidRequest<T>(T? msg, string? paramName = null)
        {
            if (msg == null)
                ThrowArgumentNull(paramName);
            else if (!(msg is global::Mediator.IBaseRequest))
                ThrowInvalidMessage(msg);
            else
                ThrowMissingHandler(msg);
        }

#if NETSTANDARD2_1_OR_GREATER
        [global::System.Diagnostics.CodeAnalysis.DoesNotReturn]
#endif
        private static void ThrowInvalidCommand<T>(T? msg, string? paramName = null)
        {
            if (msg == null)
                ThrowArgumentNull(paramName);
            else if (!(msg is global::Mediator.IBaseCommand))
                ThrowInvalidMessage(msg);
            else
                ThrowMissingHandler(msg);
        }

#if NETSTANDARD2_1_OR_GREATER
        [global::System.Diagnostics.CodeAnalysis.DoesNotReturn]
#endif
        private static void ThrowInvalidQuery<T>(T? msg, string? paramName = null)
        {
            if (msg == null)
                ThrowArgumentNull(paramName);
            else if (!(msg is global::Mediator.IBaseQuery))
                ThrowInvalidMessage(msg);
            else
                ThrowMissingHandler(msg);
        }

#if NETSTANDARD2_1_OR_GREATER
        [global::System.Diagnostics.CodeAnalysis.DoesNotReturn]
#endif
        private static void ThrowInvalidStreamMessage<T>(T? msg, string? paramName = null)
        {
            if (msg == null)
                ThrowArgumentNull(paramName);
            else if (!(msg is global::Mediator.IStreamMessage))
                ThrowInvalidMessage(msg);
            else
                ThrowMissingHandler(msg);
        }

#if NETSTANDARD2_1_OR_GREATER
        [global::System.Diagnostics.CodeAnalysis.DoesNotReturn]
#endif
        private static void ThrowInvalidStreamRequest<T>(T? msg, string? paramName = null)
        {
            if (msg == null)
                ThrowArgumentNull(paramName);
            else if (!(msg is global::Mediator.IBaseStreamRequest))
                ThrowInvalidMessage(msg);
            else
                ThrowMissingHandler(msg);
        }

#if NETSTANDARD2_1_OR_GREATER
        [global::System.Diagnostics.CodeAnalysis.DoesNotReturn]
#endif
        private static void ThrowInvalidStreamCommand<T>(T? msg, string? paramName = null)
        {
            if (msg == null)
                ThrowArgumentNull(paramName);
            else if (!(msg is global::Mediator.IBaseStreamCommand))
                ThrowInvalidMessage(msg);
            else
                ThrowMissingHandler(msg);
        }

#if NETSTANDARD2_1_OR_GREATER
        [global::System.Diagnostics.CodeAnalysis.DoesNotReturn]
#endif
        private static void ThrowInvalidStreamQuery<T>(T? msg, string? paramName = null)
        {
            if (msg == null)
                ThrowArgumentNull(paramName);
            else if (!(msg is global::Mediator.IBaseStreamQuery))
                ThrowInvalidMessage(msg);
            else
                ThrowMissingHandler(msg);
        }

#if NETSTANDARD2_1_OR_GREATER
        [global::System.Diagnostics.CodeAnalysis.DoesNotReturn]
#endif
        private static void ThrowArgumentNull(string? paramName) =>
            throw new global::System.ArgumentNullException(paramName);

#if NETSTANDARD2_1_OR_GREATER
        [global::System.Diagnostics.CodeAnalysis.DoesNotReturn]
#endif
        private static void ThrowInvalidMessage<T>(T msg) =>
            throw new global::Mediator.InvalidMessageException(msg);

        private static void ThrowIfNull<T>(T? argument, string paramName)
        {
            if (argument == null)
                ThrowArgumentNull(paramName);
        }

        private static void ThrowInvalidNotification<T>(T? argument, string paramName)
        {
            if (argument == null)
                ThrowArgumentNull(paramName);
            else if (!(argument is global::Mediator.INotification))
                ThrowInvalidMessage(argument);
        }

#if NETSTANDARD2_1_OR_GREATER
        [global::System.Diagnostics.CodeAnalysis.DoesNotReturn]
#endif
        private static void ThrowAggregateException(global::System.Collections.Generic.List<global::System.Exception> exceptions) =>
            throw new global::System.AggregateException(exceptions);

        private static void MaybeThrowAggregateException(global::System.Collections.Generic.List<global::System.Exception>? exceptions)
        {
            if (exceptions != null)
            {
                ThrowAggregateException(exceptions);
            }
        }
    }
}
