//HintName: Mediator.g.cs
// <auto-generated>
//     Generated by the Mediator source generator.
// </auto-generated>

#pragma warning disable CS8019 // Unused usings
#pragma warning disable CS8321 // Unused local function
#pragma warning disable CS1998 // Async method lacks 'await' operators and will run synchronously

#nullable enable

using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.DependencyInjection.Extensions;
using System.Linq;

namespace Microsoft.Extensions.DependencyInjection
{
    /// <summary>
    /// DI extensions for Mediator.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Mediator.SourceGenerator", "3.1.0.0")]
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.Diagnostics.DebuggerStepThroughAttribute]
    public static class MediatorDependencyInjectionExtensions
    {
        /// <summary>
        /// Adds the Mediator implementation and handlers of your application.
        /// </summary>
        public static IServiceCollection AddMediator(this IServiceCollection services)
        {
            return AddMediator(services, null);
        }

        /// <summary>
        /// Adds the Mediator implementation and handlers of your application, with specified options.
        /// </summary>
        public static IServiceCollection AddMediator(this IServiceCollection services, global::System.Action<global::Mediator.MediatorOptions>? options)
        {
            var opts = new global::Mediator.MediatorOptions();
            if (options != null)
                options(opts);

            var configuredViaAttribute = false;
            if (opts.ServiceLifetime != global::Microsoft.Extensions.DependencyInjection.ServiceLifetime.Transient && !configuredViaAttribute)
            {
                var errMsg = "Invalid configuration detected for Mediator. ";
                errMsg += "Generated code for 'Transient' lifetime, but got '" + opts.ServiceLifetime + "' lifetime from options. ";
                errMsg += "This means that the source generator hasn't seen the 'AddMediator' method call during compilation. ";
                errMsg += "Make sure that the 'AddMediator' method is called from the project that references the Mediator.SourceGenerator package.";
                throw new global::System.Exception(errMsg);
            }

            services.Add(new global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor(typeof(global::Mediator.Mediator), typeof(global::Mediator.Mediator), global::Microsoft.Extensions.DependencyInjection.ServiceLifetime.Transient));
            services.TryAdd(new global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor(typeof(global::Mediator.IMediator), typeof(global::Mediator.Mediator), global::Microsoft.Extensions.DependencyInjection.ServiceLifetime.Transient));
            services.TryAdd(new global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor(typeof(global::Mediator.ISender), typeof(global::Mediator.Mediator), global::Microsoft.Extensions.DependencyInjection.ServiceLifetime.Transient));
            services.TryAdd(new global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor(typeof(global::Mediator.IPublisher), typeof(global::Mediator.Mediator), global::Microsoft.Extensions.DependencyInjection.ServiceLifetime.Transient));

            // Register handlers for request messages
            services.Add(new global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor(typeof(global::Mediator.IRequestHandler<global::TestCode.Request, global::TestCode.Response>), typeof(global::TestCode.RequestHandler), global::Microsoft.Extensions.DependencyInjection.ServiceLifetime.Transient));
            services.Add(new global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor(typeof(global::TestCode.Request), _ => new global::Mediator.Internals.RequestHandlerWrapper<global::TestCode.Request, global::TestCode.Response>(), global::Microsoft.Extensions.DependencyInjection.ServiceLifetime.Singleton));
            services.Add(new global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor(typeof(global::Mediator.IStreamRequestHandler<global::TestCode.StreamRequest, global::TestCode.Response>), typeof(global::TestCode.RequestHandler), global::Microsoft.Extensions.DependencyInjection.ServiceLifetime.Transient));
            services.Add(new global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor(typeof(global::TestCode.StreamRequest), _ => new global::Mediator.Internals.StreamRequestHandlerWrapper<global::TestCode.StreamRequest, global::TestCode.Response>(), global::Microsoft.Extensions.DependencyInjection.ServiceLifetime.Singleton));

            // Register handlers and wrappers for notification messages
            services.Add(new global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor(typeof(global::TestCode.PingNotification), _ => new global::Mediator.Internals.NotificationHandlerWrapper<global::TestCode.PingNotification>(), global::Microsoft.Extensions.DependencyInjection.ServiceLifetime.Singleton));

            // Register notification handlers
            services.TryAdd(new global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor(typeof(global::TestCode.PingNotificationHandler), typeof(global::TestCode.PingNotificationHandler), global::Microsoft.Extensions.DependencyInjection.ServiceLifetime.Transient));
            services.Add(new global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor(typeof(global::Mediator.INotificationHandler<global::TestCode.PingNotification>), GetRequiredService<global::TestCode.PingNotificationHandler>(), global::Microsoft.Extensions.DependencyInjection.ServiceLifetime.Transient));

            // Register the notification publisher that was configured
            services.Add(new global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor(typeof(global::Mediator.TaskWhenAllPublisher), typeof(global::Mediator.TaskWhenAllPublisher), global::Microsoft.Extensions.DependencyInjection.ServiceLifetime.Transient));
            services.TryAdd(new global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor(typeof(global::Mediator.INotificationPublisher), sp => sp.GetRequiredService<global::Mediator.TaskWhenAllPublisher>(), global::Microsoft.Extensions.DependencyInjection.ServiceLifetime.Transient));

            // Register internal components
            services.Add(new global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor(typeof(global::Mediator.Internals.IContainerProbe), typeof(global::Mediator.Internals.ContainerProbe0), global::Microsoft.Extensions.DependencyInjection.ServiceLifetime.Transient));
            services.Add(new global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor(typeof(global::Mediator.Internals.IContainerProbe), typeof(global::Mediator.Internals.ContainerProbe1), global::Microsoft.Extensions.DependencyInjection.ServiceLifetime.Transient));
            services.Add(new global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor(typeof(global::Mediator.Internals.ContainerMetadata), typeof(global::Mediator.Internals.ContainerMetadata), global::Microsoft.Extensions.DependencyInjection.ServiceLifetime.Singleton));

            return services;

            [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
            static global::System.Func<global::System.IServiceProvider, T> GetRequiredService<T>() where T : notnull => sp => sp.GetRequiredService<T>();
        }
    }
}

namespace Mediator.Internals
{
    [global::System.CodeDom.Compiler.GeneratedCode("Mediator.SourceGenerator", "3.1.0.0")]
    internal interface IMessageHandlerBase
    {
        global::System.Threading.Tasks.ValueTask<object?> Handle(
            global::Mediator.Mediator mediator,
            object request,
            global::System.Threading.CancellationToken cancellationToken
        );
    }
    [global::System.CodeDom.Compiler.GeneratedCode("Mediator.SourceGenerator", "3.1.0.0")]
    internal interface INotificationHandlerBase
    {
        global::System.Threading.Tasks.ValueTask Handle(
            global::Mediator.Mediator mediator,
            object notification,
            global::System.Threading.CancellationToken cancellationToken
        );
    }
    [global::System.CodeDom.Compiler.GeneratedCode("Mediator.SourceGenerator", "3.1.0.0")]
    internal interface IStreamMessageHandlerBase
    {
        global::System.Collections.Generic.IAsyncEnumerable<object?> Handle(
            global::Mediator.Mediator mediator,
            object request,
            global::System.Threading.CancellationToken cancellationToken
        );
    }

    [global::System.CodeDom.Compiler.GeneratedCode("Mediator.SourceGenerator", "3.1.0.0")]
    internal static class MediatorTelemetry
    {
        public static readonly global::System.Diagnostics.Metrics.Meter Meter =
            new("TestMeter", "3.1.0.0");

        public static readonly global::System.Diagnostics.Metrics.Histogram<double> ProcessDuration =
            Meter.CreateHistogram<double>(
                "messaging.process.duration",
                unit: "s",
                description: "Duration of message processing operation",
                advice: new() { HistogramBucketBoundaries = new double[] { 0.005, 0.01, 0.025, 0.05, 0.075, 0.1, 0.25, 0.5, 0.75, 1, 2.5, 5, 7.5, 10 } }
            );

        public static readonly global::System.Diagnostics.ActivitySource ActivitySource =
            new("TestActivitySource", "3.1.0.0");
    }

    [global::System.CodeDom.Compiler.GeneratedCode("Mediator.SourceGenerator", "3.1.0.0")]
    internal sealed class MediatorTelemetryBehavior<TMessage, TResponse>
        : global::Mediator.IPipelineBehavior<TMessage, TResponse>
        where TMessage : global::Mediator.IMessage
    {
        private const string OperationName = "send";
        private static readonly string DestinationName = typeof(TMessage).Name;
        private static readonly string SpanName = OperationName + " " + DestinationName;
        private static readonly string MessageKind = GetMessageKind();
        private static readonly global::System.Collections.Generic.KeyValuePair<string, object?>[] TelemetryTags =
            new global::System.Collections.Generic.KeyValuePair<string, object?>[]
            {
                new global::System.Collections.Generic.KeyValuePair<string, object?>("messaging.system", "mediator"),
                new global::System.Collections.Generic.KeyValuePair<string, object?>("messaging.operation.name", OperationName),
                new global::System.Collections.Generic.KeyValuePair<string, object?>("messaging.operation.type", "process"),
                new global::System.Collections.Generic.KeyValuePair<string, object?>("messaging.mediator.message.kind", MessageKind),
                new global::System.Collections.Generic.KeyValuePair<string, object?>("messaging.destination.name", DestinationName),
            };

        private static string GetMessageKind()
        {
            if (typeof(global::Mediator.IBaseCommand).IsAssignableFrom(typeof(TMessage)))
                return "command";

            if (typeof(global::Mediator.IBaseQuery).IsAssignableFrom(typeof(TMessage)))
                return "query";

            if (typeof(global::Mediator.IBaseRequest).IsAssignableFrom(typeof(TMessage)))
                return "request";

            return "message";
        }

        public async global::System.Threading.Tasks.ValueTask<TResponse> Handle(
            TMessage message,
            global::Mediator.MessageHandlerDelegate<TMessage, TResponse> next,
            global::System.Threading.CancellationToken cancellationToken)
        {
            var startTime = global::System.Diagnostics.Stopwatch.GetTimestamp();
            var activity = global::Mediator.Internals.MediatorTelemetry.ActivitySource.StartActivity(
                SpanName,
                global::System.Diagnostics.ActivityKind.Consumer,
                default(global::System.Diagnostics.ActivityContext),
                tags: TelemetryTags
            );

            try
            {
                var response = await next(message, cancellationToken);
                MediatorTelemetry.ProcessDuration.Record(
                    global::System.Diagnostics.Stopwatch.GetElapsedTime(startTime).TotalSeconds,
                    TelemetryTags
                );
                return response;
            }
            catch (global::System.Exception ex)
            {
                if (activity is not null)
                {
                    activity.AddException(ex);
                    activity.SetStatus(global::System.Diagnostics.ActivityStatusCode.Error);
                    activity.SetTag("error.type", ex.GetType().FullName);
                }
                var tags = new global::System.Diagnostics.TagList(TelemetryTags);
                tags.Add("error.type", ex.GetType().FullName);
                MediatorTelemetry.ProcessDuration.Record(
                    global::System.Diagnostics.Stopwatch.GetElapsedTime(startTime).TotalSeconds,
                    tags
                );
                throw;
            }
            finally
            {
                activity?.Dispose();
            }
        }
    }

    [global::System.CodeDom.Compiler.GeneratedCode("Mediator.SourceGenerator", "3.1.0.0")]
    internal sealed class MediatorStreamTelemetryBehavior<TMessage, TResponse>
        : global::Mediator.IStreamPipelineBehavior<TMessage, TResponse>
        where TMessage : global::Mediator.IStreamMessage
    {
        private const string OperationName = "createstream";
        private static readonly string DestinationName = typeof(TMessage).Name;
        private static readonly string SpanName = OperationName + " " + DestinationName;
        private static readonly string MessageKind = GetMessageKind();
        private static readonly global::System.Collections.Generic.KeyValuePair<string, object?>[] TelemetryTags =
            new global::System.Collections.Generic.KeyValuePair<string, object?>[]
            {
                new global::System.Collections.Generic.KeyValuePair<string, object?>("messaging.system", "mediator"),
                new global::System.Collections.Generic.KeyValuePair<string, object?>("messaging.operation.name", OperationName),
                new global::System.Collections.Generic.KeyValuePair<string, object?>("messaging.operation.type", "process"),
                new global::System.Collections.Generic.KeyValuePair<string, object?>("messaging.mediator.message.kind", MessageKind),
                new global::System.Collections.Generic.KeyValuePair<string, object?>("messaging.destination.name", DestinationName),
            };

        private static string GetMessageKind()
        {
            if (typeof(global::Mediator.IBaseStreamCommand).IsAssignableFrom(typeof(TMessage)))
                return "streamcommand";

            if (typeof(global::Mediator.IBaseStreamQuery).IsAssignableFrom(typeof(TMessage)))
                return "streamquery";

            if (typeof(global::Mediator.IBaseStreamRequest).IsAssignableFrom(typeof(TMessage)))
                return "streamrequest";

            return "streammessage";
        }

        public global::System.Collections.Generic.IAsyncEnumerable<TResponse> Handle(
            TMessage message,
            global::Mediator.StreamHandlerDelegate<TMessage, TResponse> next,
            global::System.Threading.CancellationToken cancellationToken)
        {
            return HandleWithTelemetry(message, next, cancellationToken);
        }

        private static async global::System.Collections.Generic.IAsyncEnumerable<TResponse> HandleWithTelemetry(
            TMessage message,
            global::Mediator.StreamHandlerDelegate<TMessage, TResponse> next,
            [global::System.Runtime.CompilerServices.EnumeratorCancellation] global::System.Threading.CancellationToken cancellationToken)
        {
            var startTime = global::System.Diagnostics.Stopwatch.GetTimestamp();
            string? errorType = null;
            var activity = global::Mediator.Internals.MediatorTelemetry.ActivitySource.StartActivity(
                SpanName,
                global::System.Diagnostics.ActivityKind.Consumer,
                default(global::System.Diagnostics.ActivityContext),
                tags: TelemetryTags
            );

            global::System.Collections.Generic.IAsyncEnumerator<TResponse> enumerator;
            try
            {
                var responses = next(message, cancellationToken);
                enumerator = responses.GetAsyncEnumerator(cancellationToken);
            }
            catch (global::System.Exception ex)
            {
                if (activity is not null)
                {
                    activity.AddException(ex);
                    activity.SetStatus(global::System.Diagnostics.ActivityStatusCode.Error);
                    activity.SetTag("error.type", ex.GetType().FullName);
                }
                var tags = new global::System.Diagnostics.TagList(TelemetryTags);
                tags.Add("error.type", ex.GetType().FullName);
                MediatorTelemetry.ProcessDuration.Record(
                    global::System.Diagnostics.Stopwatch.GetElapsedTime(startTime).TotalSeconds,
                    tags
                );
                activity?.Dispose();
                throw;
            }
            await using var asyncEnumerator = enumerator;
            try
            {
                while (true)
                {
                    TResponse response;
                    try
                    {
                        if (!await asyncEnumerator.MoveNextAsync())
                            break;
                        response = asyncEnumerator.Current;
                    }
                    catch (global::System.Exception ex)
                    {
                        if (activity is not null)
                        {
                            activity.AddException(ex);
                            activity.SetStatus(global::System.Diagnostics.ActivityStatusCode.Error);
                            activity.SetTag("error.type", ex.GetType().FullName);
                        }
                        errorType = ex.GetType().FullName;
                        throw;
                    }

                    yield return response;
                }
            }
            finally
            {
                if (errorType is null)
                {
                    MediatorTelemetry.ProcessDuration.Record(
                        global::System.Diagnostics.Stopwatch.GetElapsedTime(startTime).TotalSeconds,
                        TelemetryTags
                    );
                }
                else
                {
                    var tags = new global::System.Diagnostics.TagList(TelemetryTags);
                    tags.Add("error.type", errorType);
                    MediatorTelemetry.ProcessDuration.Record(
                        global::System.Diagnostics.Stopwatch.GetElapsedTime(startTime).TotalSeconds,
                        tags
                    );
                }
                activity?.Dispose();
            }
        }
    }

    [global::System.CodeDom.Compiler.GeneratedCode("Mediator.SourceGenerator", "3.1.0.0")]
    internal sealed class MediatorTelemetryNotificationPublisher
        : global::Mediator.INotificationPublisher
    {
        private readonly global::Mediator.TaskWhenAllPublisher _inner;
        private static class NotificationTelemetry<TNotificationType>
            where TNotificationType : global::Mediator.INotification
        {
            public const string OperationName = "publish";
            public static readonly string DestinationName = typeof(TNotificationType).Name;
            public static readonly string SpanName = OperationName + " " + DestinationName;
            public static readonly global::System.Collections.Generic.KeyValuePair<string, object?>[] TelemetryTags =
                new global::System.Collections.Generic.KeyValuePair<string, object?>[]
                {
                    new global::System.Collections.Generic.KeyValuePair<string, object?>("messaging.system", "mediator"),
                    new global::System.Collections.Generic.KeyValuePair<string, object?>("messaging.operation.name", OperationName),
                    new global::System.Collections.Generic.KeyValuePair<string, object?>("messaging.operation.type", "process"),
                    new global::System.Collections.Generic.KeyValuePair<string, object?>("messaging.mediator.message.kind", "notification"),
                    new global::System.Collections.Generic.KeyValuePair<string, object?>("messaging.destination.name", DestinationName),
                };
        }

        public MediatorTelemetryNotificationPublisher(global::Mediator.TaskWhenAllPublisher inner)
        {
            _inner = inner;
        }

        public async global::System.Threading.Tasks.ValueTask Publish<TNotification>(
            global::Mediator.NotificationHandlers<TNotification> handlers,
            TNotification notification,
            global::System.Threading.CancellationToken cancellationToken)
            where TNotification : global::Mediator.INotification
        {
            var telemetryTags = NotificationTelemetry<TNotification>.TelemetryTags;
            var startTime = global::System.Diagnostics.Stopwatch.GetTimestamp();
            var activity = global::Mediator.Internals.MediatorTelemetry.ActivitySource.StartActivity(
                NotificationTelemetry<TNotification>.SpanName,
                global::System.Diagnostics.ActivityKind.Consumer,
                default(global::System.Diagnostics.ActivityContext),
                tags: telemetryTags
            );

            try
            {
                await _inner.Publish(handlers, notification, cancellationToken);
                MediatorTelemetry.ProcessDuration.Record(
                    global::System.Diagnostics.Stopwatch.GetElapsedTime(startTime).TotalSeconds,
                    telemetryTags
                );
            }
            catch (global::System.Exception ex)
            {
                if (activity is not null)
                {
                    activity.AddException(ex);
                    activity.SetStatus(global::System.Diagnostics.ActivityStatusCode.Error);
                    activity.SetTag("error.type", ex.GetType().FullName);
                }
                var tags = new global::System.Diagnostics.TagList(telemetryTags);
                tags.Add("error.type", ex.GetType().FullName);
                MediatorTelemetry.ProcessDuration.Record(
                    global::System.Diagnostics.Stopwatch.GetElapsedTime(startTime).TotalSeconds,
                    tags
                );
                throw;
            }
            finally
            {
                activity?.Dispose();
            }
        }
    }

    [global::System.CodeDom.Compiler.GeneratedCode("Mediator.SourceGenerator", "3.1.0.0")]
    internal interface IRequestHandlerBase<TResponse> : IMessageHandlerBase
    {
        global::System.Threading.Tasks.ValueTask<TResponse> Handle(
            global::Mediator.Mediator mediator,
            global::Mediator.IRequest<TResponse> request,
            global::System.Threading.CancellationToken cancellationToken
        );
    }
    [global::System.CodeDom.Compiler.GeneratedCode("Mediator.SourceGenerator", "3.1.0.0")]
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.Diagnostics.DebuggerStepThroughAttribute]
    internal sealed class RequestHandlerWrapper<TRequest, TResponse> : IRequestHandlerBase<TResponse>
        where TRequest : global::Mediator.IRequest<TResponse>
    {

        public global::System.Threading.Tasks.ValueTask<TResponse> Handle(
            global::Mediator.Mediator mediator,
            TRequest request,
            global::System.Threading.CancellationToken cancellationToken
        )
        {
            var concreteHandler = mediator.Services.GetRequiredService<global::Mediator.IRequestHandler<TRequest, TResponse>>();
            var pipelineBehaviours = mediator.Services.GetServices<global::Mediator.IPipelineBehavior<TRequest, TResponse>>();
            var handler = (global::Mediator.MessageHandlerDelegate<TRequest, TResponse>)concreteHandler.Handle;

            global::Mediator.IPipelineBehavior<TRequest, TResponse>[] pipelineBehavioursArray;
            if (mediator.ServicesUnderlyingTypeIsArray)
            {
                global::System.Diagnostics.Debug.Assert(
                    pipelineBehaviours is global::Mediator.IPipelineBehavior<TRequest, TResponse>[]
                );
                pipelineBehavioursArray = global::System.Runtime.CompilerServices.Unsafe.As<global::Mediator.IPipelineBehavior<TRequest, TResponse>[]>(
                    pipelineBehaviours
                );
                for (int i = pipelineBehavioursArray.Length - 1; i >= 0; i--)
                {
                    var pipeline = pipelineBehavioursArray[i];
                    var handlerCopy = handler;
                    var pipelineCopy = pipeline;
                    handler = (TRequest message, System.Threading.CancellationToken cancellationToken) => pipelineCopy.Handle(message, handlerCopy, cancellationToken);
                }
            }
            else
            {
                global::System.Diagnostics.Debug.Assert(
                    pipelineBehaviours is not global::Mediator.IPipelineBehavior<TRequest, TResponse>[]
                );
                foreach (var pipeline in pipelineBehaviours.Reverse())
                {
                    var handlerCopy = handler;
                    var pipelineCopy = pipeline;
                    handler = (TRequest message, System.Threading.CancellationToken cancellationToken) => pipelineCopy.Handle(message, handlerCopy, cancellationToken);
                }
            }
            {
                var handlerCopy = handler;
                var telemetryBehavior = new global::Mediator.Internals.MediatorTelemetryBehavior<TRequest, TResponse>();
                handler = (TRequest message, System.Threading.CancellationToken cancellationToken) => telemetryBehavior.Handle(message, handlerCopy, cancellationToken);
            }
            return handler(request, cancellationToken);
        }

        public global::System.Threading.Tasks.ValueTask<TResponse> Handle(
            global::Mediator.Mediator mediator,
            global::Mediator.IRequest<TResponse> request,
            global::System.Threading.CancellationToken cancellationToken
        )
        {
            return Handle(mediator, (TRequest)request, cancellationToken);
        }

        public async global::System.Threading.Tasks.ValueTask<object?> Handle(
            global::Mediator.Mediator mediator,
            object request,
            global::System.Threading.CancellationToken cancellationToken
        )
        {
            return await Handle(mediator, (TRequest)request, cancellationToken);
        }
    }
    [global::System.CodeDom.Compiler.GeneratedCode("Mediator.SourceGenerator", "3.1.0.0")]
    internal interface IStreamRequestHandlerBase<TResponse> : IStreamMessageHandlerBase
    {
        global::System.Collections.Generic.IAsyncEnumerable<TResponse> Handle(
            global::Mediator.Mediator mediator,
            global::Mediator.IStreamRequest<TResponse> request,
            global::System.Threading.CancellationToken cancellationToken
        );
    }
    [global::System.CodeDom.Compiler.GeneratedCode("Mediator.SourceGenerator", "3.1.0.0")]
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.Diagnostics.DebuggerStepThroughAttribute]
    internal sealed class StreamRequestHandlerWrapper<TRequest, TResponse> : IStreamRequestHandlerBase<TResponse>
        where TRequest : global::Mediator.IStreamRequest<TResponse>
    {

        public global::System.Collections.Generic.IAsyncEnumerable<TResponse> Handle(
            global::Mediator.Mediator mediator,
            TRequest request,
            global::System.Threading.CancellationToken cancellationToken
        )
        {
            var concreteHandler = mediator.Services.GetRequiredService<global::Mediator.IStreamRequestHandler<TRequest, TResponse>>();
            var pipelineBehaviours = mediator.Services.GetServices<global::Mediator.IStreamPipelineBehavior<TRequest, TResponse>>();
            var handler = (global::Mediator.StreamHandlerDelegate<TRequest, TResponse>)concreteHandler.Handle;

            global::Mediator.IStreamPipelineBehavior<TRequest, TResponse>[] pipelineBehavioursArray;
            if (mediator.ServicesUnderlyingTypeIsArray)
            {
                global::System.Diagnostics.Debug.Assert(
                    pipelineBehaviours is global::Mediator.IStreamPipelineBehavior<TRequest, TResponse>[]
                );
                pipelineBehavioursArray = global::System.Runtime.CompilerServices.Unsafe.As<global::Mediator.IStreamPipelineBehavior<TRequest, TResponse>[]>(
                    pipelineBehaviours
                );
                for (int i = pipelineBehavioursArray.Length - 1; i >= 0; i--)
                {
                    var pipeline = pipelineBehavioursArray[i];
                    var handlerCopy = handler;
                    var pipelineCopy = pipeline;
                    handler = (TRequest message, System.Threading.CancellationToken cancellationToken) => pipelineCopy.Handle(message, handlerCopy, cancellationToken);
                }
            }
            else
            {
                global::System.Diagnostics.Debug.Assert(
                    pipelineBehaviours is not global::Mediator.IStreamPipelineBehavior<TRequest, TResponse>[]
                );
                foreach (var pipeline in pipelineBehaviours.Reverse())
                {
                    var handlerCopy = handler;
                    var pipelineCopy = pipeline;
                    handler = (TRequest message, System.Threading.CancellationToken cancellationToken) => pipelineCopy.Handle(message, handlerCopy, cancellationToken);
                }
            }
            {
                var handlerCopy = handler;
                var telemetryBehavior = new global::Mediator.Internals.MediatorStreamTelemetryBehavior<TRequest, TResponse>();
                handler = (TRequest message, System.Threading.CancellationToken cancellationToken) => telemetryBehavior.Handle(message, handlerCopy, cancellationToken);
            }
            return handler(request, cancellationToken);
        }

        public global::System.Collections.Generic.IAsyncEnumerable<TResponse> Handle(
            global::Mediator.Mediator mediator,
            global::Mediator.IStreamRequest<TResponse> request,
            global::System.Threading.CancellationToken cancellationToken
        )
        {
            return Handle(mediator, (TRequest)request, cancellationToken);
        }

        public async global::System.Collections.Generic.IAsyncEnumerable<object?> Handle(
            global::Mediator.Mediator mediator,
            object request,
            [global::System.Runtime.CompilerServices.EnumeratorCancellation] global::System.Threading.CancellationToken cancellationToken
        )
        {
            await foreach (var el in Handle(mediator, (TRequest)request, cancellationToken))
                yield return el;
        }
    }
    [global::System.CodeDom.Compiler.GeneratedCode("Mediator.SourceGenerator", "3.1.0.0")]
    internal interface ICommandHandlerBase<TResponse> : IMessageHandlerBase
    {
        global::System.Threading.Tasks.ValueTask<TResponse> Handle(
            global::Mediator.Mediator mediator,
            global::Mediator.ICommand<TResponse> request,
            global::System.Threading.CancellationToken cancellationToken
        );
    }
    [global::System.CodeDom.Compiler.GeneratedCode("Mediator.SourceGenerator", "3.1.0.0")]
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.Diagnostics.DebuggerStepThroughAttribute]
    internal sealed class CommandHandlerWrapper<TRequest, TResponse> : ICommandHandlerBase<TResponse>
        where TRequest : global::Mediator.ICommand<TResponse>
    {

        public global::System.Threading.Tasks.ValueTask<TResponse> Handle(
            global::Mediator.Mediator mediator,
            TRequest request,
            global::System.Threading.CancellationToken cancellationToken
        )
        {
            var concreteHandler = mediator.Services.GetRequiredService<global::Mediator.ICommandHandler<TRequest, TResponse>>();
            var pipelineBehaviours = mediator.Services.GetServices<global::Mediator.IPipelineBehavior<TRequest, TResponse>>();
            var handler = (global::Mediator.MessageHandlerDelegate<TRequest, TResponse>)concreteHandler.Handle;

            global::Mediator.IPipelineBehavior<TRequest, TResponse>[] pipelineBehavioursArray;
            if (mediator.ServicesUnderlyingTypeIsArray)
            {
                global::System.Diagnostics.Debug.Assert(
                    pipelineBehaviours is global::Mediator.IPipelineBehavior<TRequest, TResponse>[]
                );
                pipelineBehavioursArray = global::System.Runtime.CompilerServices.Unsafe.As<global::Mediator.IPipelineBehavior<TRequest, TResponse>[]>(
                    pipelineBehaviours
                );
                for (int i = pipelineBehavioursArray.Length - 1; i >= 0; i--)
                {
                    var pipeline = pipelineBehavioursArray[i];
                    var handlerCopy = handler;
                    var pipelineCopy = pipeline;
                    handler = (TRequest message, System.Threading.CancellationToken cancellationToken) => pipelineCopy.Handle(message, handlerCopy, cancellationToken);
                }
            }
            else
            {
                global::System.Diagnostics.Debug.Assert(
                    pipelineBehaviours is not global::Mediator.IPipelineBehavior<TRequest, TResponse>[]
                );
                foreach (var pipeline in pipelineBehaviours.Reverse())
                {
                    var handlerCopy = handler;
                    var pipelineCopy = pipeline;
                    handler = (TRequest message, System.Threading.CancellationToken cancellationToken) => pipelineCopy.Handle(message, handlerCopy, cancellationToken);
                }
            }
            {
                var handlerCopy = handler;
                var telemetryBehavior = new global::Mediator.Internals.MediatorTelemetryBehavior<TRequest, TResponse>();
                handler = (TRequest message, System.Threading.CancellationToken cancellationToken) => telemetryBehavior.Handle(message, handlerCopy, cancellationToken);
            }
            return handler(request, cancellationToken);
        }

        public global::System.Threading.Tasks.ValueTask<TResponse> Handle(
            global::Mediator.Mediator mediator,
            global::Mediator.ICommand<TResponse> request,
            global::System.Threading.CancellationToken cancellationToken
        )
        {
            return Handle(mediator, (TRequest)request, cancellationToken);
        }

        public async global::System.Threading.Tasks.ValueTask<object?> Handle(
            global::Mediator.Mediator mediator,
            object request,
            global::System.Threading.CancellationToken cancellationToken
        )
        {
            return await Handle(mediator, (TRequest)request, cancellationToken);
        }
    }
    [global::System.CodeDom.Compiler.GeneratedCode("Mediator.SourceGenerator", "3.1.0.0")]
    internal interface IStreamCommandHandlerBase<TResponse> : IStreamMessageHandlerBase
    {
        global::System.Collections.Generic.IAsyncEnumerable<TResponse> Handle(
            global::Mediator.Mediator mediator,
            global::Mediator.IStreamCommand<TResponse> request,
            global::System.Threading.CancellationToken cancellationToken
        );
    }
    [global::System.CodeDom.Compiler.GeneratedCode("Mediator.SourceGenerator", "3.1.0.0")]
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.Diagnostics.DebuggerStepThroughAttribute]
    internal sealed class StreamCommandHandlerWrapper<TRequest, TResponse> : IStreamCommandHandlerBase<TResponse>
        where TRequest : global::Mediator.IStreamCommand<TResponse>
    {

        public global::System.Collections.Generic.IAsyncEnumerable<TResponse> Handle(
            global::Mediator.Mediator mediator,
            TRequest request,
            global::System.Threading.CancellationToken cancellationToken
        )
        {
            var concreteHandler = mediator.Services.GetRequiredService<global::Mediator.IStreamCommandHandler<TRequest, TResponse>>();
            var pipelineBehaviours = mediator.Services.GetServices<global::Mediator.IStreamPipelineBehavior<TRequest, TResponse>>();
            var handler = (global::Mediator.StreamHandlerDelegate<TRequest, TResponse>)concreteHandler.Handle;

            global::Mediator.IStreamPipelineBehavior<TRequest, TResponse>[] pipelineBehavioursArray;
            if (mediator.ServicesUnderlyingTypeIsArray)
            {
                global::System.Diagnostics.Debug.Assert(
                    pipelineBehaviours is global::Mediator.IStreamPipelineBehavior<TRequest, TResponse>[]
                );
                pipelineBehavioursArray = global::System.Runtime.CompilerServices.Unsafe.As<global::Mediator.IStreamPipelineBehavior<TRequest, TResponse>[]>(
                    pipelineBehaviours
                );
                for (int i = pipelineBehavioursArray.Length - 1; i >= 0; i--)
                {
                    var pipeline = pipelineBehavioursArray[i];
                    var handlerCopy = handler;
                    var pipelineCopy = pipeline;
                    handler = (TRequest message, System.Threading.CancellationToken cancellationToken) => pipelineCopy.Handle(message, handlerCopy, cancellationToken);
                }
            }
            else
            {
                global::System.Diagnostics.Debug.Assert(
                    pipelineBehaviours is not global::Mediator.IStreamPipelineBehavior<TRequest, TResponse>[]
                );
                foreach (var pipeline in pipelineBehaviours.Reverse())
                {
                    var handlerCopy = handler;
                    var pipelineCopy = pipeline;
                    handler = (TRequest message, System.Threading.CancellationToken cancellationToken) => pipelineCopy.Handle(message, handlerCopy, cancellationToken);
                }
            }
            {
                var handlerCopy = handler;
                var telemetryBehavior = new global::Mediator.Internals.MediatorStreamTelemetryBehavior<TRequest, TResponse>();
                handler = (TRequest message, System.Threading.CancellationToken cancellationToken) => telemetryBehavior.Handle(message, handlerCopy, cancellationToken);
            }
            return handler(request, cancellationToken);
        }

        public global::System.Collections.Generic.IAsyncEnumerable<TResponse> Handle(
            global::Mediator.Mediator mediator,
            global::Mediator.IStreamCommand<TResponse> request,
            global::System.Threading.CancellationToken cancellationToken
        )
        {
            return Handle(mediator, (TRequest)request, cancellationToken);
        }

        public async global::System.Collections.Generic.IAsyncEnumerable<object?> Handle(
            global::Mediator.Mediator mediator,
            object request,
            [global::System.Runtime.CompilerServices.EnumeratorCancellation] global::System.Threading.CancellationToken cancellationToken
        )
        {
            await foreach (var el in Handle(mediator, (TRequest)request, cancellationToken))
                yield return el;
        }
    }
    [global::System.CodeDom.Compiler.GeneratedCode("Mediator.SourceGenerator", "3.1.0.0")]
    internal interface IQueryHandlerBase<TResponse> : IMessageHandlerBase
    {
        global::System.Threading.Tasks.ValueTask<TResponse> Handle(
            global::Mediator.Mediator mediator,
            global::Mediator.IQuery<TResponse> request,
            global::System.Threading.CancellationToken cancellationToken
        );
    }
    [global::System.CodeDom.Compiler.GeneratedCode("Mediator.SourceGenerator", "3.1.0.0")]
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.Diagnostics.DebuggerStepThroughAttribute]
    internal sealed class QueryHandlerWrapper<TRequest, TResponse> : IQueryHandlerBase<TResponse>
        where TRequest : global::Mediator.IQuery<TResponse>
    {

        public global::System.Threading.Tasks.ValueTask<TResponse> Handle(
            global::Mediator.Mediator mediator,
            TRequest request,
            global::System.Threading.CancellationToken cancellationToken
        )
        {
            var concreteHandler = mediator.Services.GetRequiredService<global::Mediator.IQueryHandler<TRequest, TResponse>>();
            var pipelineBehaviours = mediator.Services.GetServices<global::Mediator.IPipelineBehavior<TRequest, TResponse>>();
            var handler = (global::Mediator.MessageHandlerDelegate<TRequest, TResponse>)concreteHandler.Handle;

            global::Mediator.IPipelineBehavior<TRequest, TResponse>[] pipelineBehavioursArray;
            if (mediator.ServicesUnderlyingTypeIsArray)
            {
                global::System.Diagnostics.Debug.Assert(
                    pipelineBehaviours is global::Mediator.IPipelineBehavior<TRequest, TResponse>[]
                );
                pipelineBehavioursArray = global::System.Runtime.CompilerServices.Unsafe.As<global::Mediator.IPipelineBehavior<TRequest, TResponse>[]>(
                    pipelineBehaviours
                );
                for (int i = pipelineBehavioursArray.Length - 1; i >= 0; i--)
                {
                    var pipeline = pipelineBehavioursArray[i];
                    var handlerCopy = handler;
                    var pipelineCopy = pipeline;
                    handler = (TRequest message, System.Threading.CancellationToken cancellationToken) => pipelineCopy.Handle(message, handlerCopy, cancellationToken);
                }
            }
            else
            {
                global::System.Diagnostics.Debug.Assert(
                    pipelineBehaviours is not global::Mediator.IPipelineBehavior<TRequest, TResponse>[]
                );
                foreach (var pipeline in pipelineBehaviours.Reverse())
                {
                    var handlerCopy = handler;
                    var pipelineCopy = pipeline;
                    handler = (TRequest message, System.Threading.CancellationToken cancellationToken) => pipelineCopy.Handle(message, handlerCopy, cancellationToken);
                }
            }
            {
                var handlerCopy = handler;
                var telemetryBehavior = new global::Mediator.Internals.MediatorTelemetryBehavior<TRequest, TResponse>();
                handler = (TRequest message, System.Threading.CancellationToken cancellationToken) => telemetryBehavior.Handle(message, handlerCopy, cancellationToken);
            }
            return handler(request, cancellationToken);
        }

        public global::System.Threading.Tasks.ValueTask<TResponse> Handle(
            global::Mediator.Mediator mediator,
            global::Mediator.IQuery<TResponse> request,
            global::System.Threading.CancellationToken cancellationToken
        )
        {
            return Handle(mediator, (TRequest)request, cancellationToken);
        }

        public async global::System.Threading.Tasks.ValueTask<object?> Handle(
            global::Mediator.Mediator mediator,
            object request,
            global::System.Threading.CancellationToken cancellationToken
        )
        {
            return await Handle(mediator, (TRequest)request, cancellationToken);
        }
    }
    [global::System.CodeDom.Compiler.GeneratedCode("Mediator.SourceGenerator", "3.1.0.0")]
    internal interface IStreamQueryHandlerBase<TResponse> : IStreamMessageHandlerBase
    {
        global::System.Collections.Generic.IAsyncEnumerable<TResponse> Handle(
            global::Mediator.Mediator mediator,
            global::Mediator.IStreamQuery<TResponse> request,
            global::System.Threading.CancellationToken cancellationToken
        );
    }
    [global::System.CodeDom.Compiler.GeneratedCode("Mediator.SourceGenerator", "3.1.0.0")]
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.Diagnostics.DebuggerStepThroughAttribute]
    internal sealed class StreamQueryHandlerWrapper<TRequest, TResponse> : IStreamQueryHandlerBase<TResponse>
        where TRequest : global::Mediator.IStreamQuery<TResponse>
    {

        public global::System.Collections.Generic.IAsyncEnumerable<TResponse> Handle(
            global::Mediator.Mediator mediator,
            TRequest request,
            global::System.Threading.CancellationToken cancellationToken
        )
        {
            var concreteHandler = mediator.Services.GetRequiredService<global::Mediator.IStreamQueryHandler<TRequest, TResponse>>();
            var pipelineBehaviours = mediator.Services.GetServices<global::Mediator.IStreamPipelineBehavior<TRequest, TResponse>>();
            var handler = (global::Mediator.StreamHandlerDelegate<TRequest, TResponse>)concreteHandler.Handle;

            global::Mediator.IStreamPipelineBehavior<TRequest, TResponse>[] pipelineBehavioursArray;
            if (mediator.ServicesUnderlyingTypeIsArray)
            {
                global::System.Diagnostics.Debug.Assert(
                    pipelineBehaviours is global::Mediator.IStreamPipelineBehavior<TRequest, TResponse>[]
                );
                pipelineBehavioursArray = global::System.Runtime.CompilerServices.Unsafe.As<global::Mediator.IStreamPipelineBehavior<TRequest, TResponse>[]>(
                    pipelineBehaviours
                );
                for (int i = pipelineBehavioursArray.Length - 1; i >= 0; i--)
                {
                    var pipeline = pipelineBehavioursArray[i];
                    var handlerCopy = handler;
                    var pipelineCopy = pipeline;
                    handler = (TRequest message, System.Threading.CancellationToken cancellationToken) => pipelineCopy.Handle(message, handlerCopy, cancellationToken);
                }
            }
            else
            {
                global::System.Diagnostics.Debug.Assert(
                    pipelineBehaviours is not global::Mediator.IStreamPipelineBehavior<TRequest, TResponse>[]
                );
                foreach (var pipeline in pipelineBehaviours.Reverse())
                {
                    var handlerCopy = handler;
                    var pipelineCopy = pipeline;
                    handler = (TRequest message, System.Threading.CancellationToken cancellationToken) => pipelineCopy.Handle(message, handlerCopy, cancellationToken);
                }
            }
            {
                var handlerCopy = handler;
                var telemetryBehavior = new global::Mediator.Internals.MediatorStreamTelemetryBehavior<TRequest, TResponse>();
                handler = (TRequest message, System.Threading.CancellationToken cancellationToken) => telemetryBehavior.Handle(message, handlerCopy, cancellationToken);
            }
            return handler(request, cancellationToken);
        }

        public global::System.Collections.Generic.IAsyncEnumerable<TResponse> Handle(
            global::Mediator.Mediator mediator,
            global::Mediator.IStreamQuery<TResponse> request,
            global::System.Threading.CancellationToken cancellationToken
        )
        {
            return Handle(mediator, (TRequest)request, cancellationToken);
        }

        public async global::System.Collections.Generic.IAsyncEnumerable<object?> Handle(
            global::Mediator.Mediator mediator,
            object request,
            [global::System.Runtime.CompilerServices.EnumeratorCancellation] global::System.Threading.CancellationToken cancellationToken
        )
        {
            await foreach (var el in Handle(mediator, (TRequest)request, cancellationToken))
                yield return el;
        }
    }

    [global::System.CodeDom.Compiler.GeneratedCode("Mediator.SourceGenerator", "3.1.0.0")]
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.Diagnostics.DebuggerStepThroughAttribute]
    internal sealed class NotificationHandlerWrapper<TNotification> : INotificationHandlerBase
        where TNotification : global::Mediator.INotification
    {

        public global::System.Threading.Tasks.ValueTask Handle(
            global::Mediator.Mediator mediator,
            TNotification notification,
            global::System.Threading.CancellationToken cancellationToken
        )
        {
            var handlers = mediator.Services.GetServices<global::Mediator.INotificationHandler<TNotification>>();
            var isArray = mediator.ServicesUnderlyingTypeIsArray;
            if (isArray)
            {
                global::System.Diagnostics.Debug.Assert(
                    handlers is global::Mediator.INotificationHandler<TNotification>[],
                    $"Unexpected type: {handlers.GetType()}"
                );
                if (global::System.Runtime.CompilerServices.Unsafe.As<global::Mediator.INotificationHandler<TNotification>[]>(handlers).Length == 0)
                {
                    return default;
                }
            }
            else
            {
                global::System.Diagnostics.Debug.Assert(
                    handlers is not global::Mediator.INotificationHandler<TNotification>[],
                    $"Unexpected type: {handlers.GetType()}"
                );
            }
            return mediator.NotificationPublisher.Publish(
                new global::Mediator.NotificationHandlers<TNotification>(handlers, isArray),
                notification,
                cancellationToken
            );
        }

        public global::System.Threading.Tasks.ValueTask Handle(
            global::Mediator.Mediator mediator,
            object notification,
            global::System.Threading.CancellationToken cancellationToken
        )
        {
            return Handle(mediator, (TNotification)notification, cancellationToken);
        }
    }

    internal interface IContainerProbe { }
    internal sealed class ContainerProbe0 : IContainerProbe { }
    internal sealed class ContainerProbe1 : IContainerProbe { }

    [global::System.CodeDom.Compiler.GeneratedCode("Mediator.SourceGenerator", "3.1.0.0")]
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.Diagnostics.DebuggerStepThroughAttribute]
    internal sealed class ContainerMetadata
    {
        public readonly bool ServicesUnderlyingTypeIsArray;

        public ContainerMetadata(global::System.IServiceProvider sp)
        {
            ServicesUnderlyingTypeIsArray = sp.GetServices<global::Mediator.Internals.IContainerProbe>() is global::Mediator.Internals.IContainerProbe[];
        }
    }
}

namespace Mediator
{
    /// <summary>
    /// Generated code for Mediator implementation.
    /// This type is also registered as a DI service.
    /// Can be used directly for high performance scenarios.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Mediator.SourceGenerator", "3.1.0.0")]
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.Diagnostics.DebuggerStepThroughAttribute]
    public sealed partial class Mediator : global::Mediator.IMediator, global::Mediator.ISender, global::Mediator.IPublisher
    {
        internal readonly global::System.IServiceProvider Services;
        private global::Mediator.Internals.MediatorTelemetryNotificationPublisher? _notificationPublisher;
        internal global::Mediator.Internals.MediatorTelemetryNotificationPublisher NotificationPublisher
        {
            [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
            get
            {
                if (_notificationPublisher == null)
                {
                    var notificationPublisher = Services.GetRequiredService<global::Mediator.TaskWhenAllPublisher>();
                    _notificationPublisher = new global::Mediator.Internals.MediatorTelemetryNotificationPublisher(notificationPublisher);
                }
                return _notificationPublisher!;
            }
        }
        private global::Mediator.Internals.ContainerMetadata? _containerMetadataStorage;
        private global::Mediator.Internals.ContainerMetadata _containerMetadata
        {
            [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
            get
            {
                if (_containerMetadataStorage == null)
                {
                    var containerMetadata = Services.GetRequiredService<global::Mediator.Internals.ContainerMetadata>();
                    _containerMetadataStorage = containerMetadata;
                    return containerMetadata;
                }
                return _containerMetadataStorage;
            }
        }
        internal bool ServicesUnderlyingTypeIsArray => _containerMetadata.ServicesUnderlyingTypeIsArray;

        /// <summary>
        /// The lifetime of Mediator-related service registrations in DI container.
        /// </summary>
        public const global::Microsoft.Extensions.DependencyInjection.ServiceLifetime ServiceLifetime = global::Microsoft.Extensions.DependencyInjection.ServiceLifetime.Transient;

        /// <summary>
        /// The caching mode configuration for Mediator handler resolution.
        /// </summary>
        public const global::Mediator.CachingMode CachingMode = global::Mediator.CachingMode.Lazy;

        /// <summary>
        /// The name of the notification publisher service that was configured.
        /// </summary>
        public const string NotificationPublisherName = "TaskWhenAllPublisher";

        /// <summary>
        /// The total number of Mediator messages that were discovered.
        /// </summary>
        public const int TotalMessages = 3;

        /// <summary>
        /// The configured telemetry meter name.
        /// </summary>
        public const string MeterName = "TestMeter";

        /// <summary>
        /// The configured telemetry activity source name.
        /// </summary>
        public const string ActivitySourceName = "TestActivitySource";

        /// <summary>
        /// Constructor for DI, should not be used by consumer.
        /// </summary>
        public Mediator(global::System.IServiceProvider sp)
        {
            Services = sp;
        }



        /// <summary>
        /// Send a request of type global::TestCode.Request.
        /// </summary>
        /// <param name="request">Incoming request</param>
        /// <param name="cancellationToken">Cancellation token</param>
        /// <returns>Awaitable task</returns>
        public global::System.Threading.Tasks.ValueTask<global::TestCode.Response> Send(
            global::TestCode.Request request,
            global::System.Threading.CancellationToken cancellationToken = default
        )
        {
            var wrapperObj = Services.GetService(typeof(global::TestCode.Request));
            var wrapper = wrapperObj as global::Mediator.Internals.RequestHandlerWrapper<global::TestCode.Request, global::TestCode.Response>;
            if (wrapper == null)
                ThrowMissingHandler(request);
            return wrapper!.Handle(this, request, cancellationToken);
        }

        /// <summary>
        /// Create a stream from request type global::TestCode.StreamRequest.
        /// </summary>
        /// <param name="request">Incoming request</param>
        /// <param name="cancellationToken">Cancellation token</param>
        /// <returns>Awaitable task</returns>
        public global::System.Collections.Generic.IAsyncEnumerable<global::TestCode.Response> CreateStream(
            global::TestCode.StreamRequest request,
            global::System.Threading.CancellationToken cancellationToken = default
        )
        {
            var wrapperObj = Services.GetService(typeof(global::TestCode.StreamRequest));
            var wrapper = wrapperObj as global::Mediator.Internals.StreamRequestHandlerWrapper<global::TestCode.StreamRequest, global::TestCode.Response>;
            if (wrapper == null)
                ThrowMissingHandler(request);
            return wrapper!.Handle(this, request, cancellationToken);
        }

        /// <summary>
        /// Send request.
        /// Throws <see cref="global::System.ArgumentNullException"/> if message is null.
        /// Throws <see cref="global::Mediator.InvalidMessageException"/> if request does not implement <see cref="global::Mediator.IRequest{TResponse}"/>.
        /// Throws <see cref="global::Mediator.MissingMessageHandlerException"/> if no handler is registered.
        /// </summary>
        /// <param name="request">Incoming request</param>
        /// <param name="cancellationToken">Cancellation token</param>
        /// <returns>Awaitable task</returns>
        public global::System.Threading.Tasks.ValueTask<TResponse> Send<TResponse>(
            global::Mediator.IRequest<TResponse> request,
            global::System.Threading.CancellationToken cancellationToken = default
        )
        {
            switch (request)
            {
                case global::TestCode.Request r:
                {
                    if (typeof(TResponse) == typeof(global::TestCode.Response))
                    {
                        var task = Send(r, cancellationToken);
                        return global::System.Runtime.CompilerServices.Unsafe.As<global::System.Threading.Tasks.ValueTask<global::TestCode.Response>, global::System.Threading.Tasks.ValueTask<TResponse>>(ref task);
                    }
                    return SendAsync(request, cancellationToken);
                }
                default:
                {
                    ThrowInvalidRequest(request, nameof(request));
                    return default;
                }
            }
        }

        private async global::System.Threading.Tasks.ValueTask<TResponse> SendAsync<TResponse>(
            global::Mediator.IRequest<TResponse> request,
            global::System.Threading.CancellationToken cancellationToken = default
        )
        {
            switch (request)
            {
                case global::TestCode.Request r:
                {
                    var response = await Send(r, cancellationToken);
                    return global::System.Runtime.CompilerServices.Unsafe.As<global::TestCode.Response, TResponse>(ref response);
                }
                default:
                {
                    ThrowInvalidRequest(request, nameof(request));
                    return default!;
                }
            }
        }

        /// <summary>
        /// Create stream for request.
        /// Throws <see cref="global::System.ArgumentNullException"/> if message is null.
        /// Throws <see cref="global::Mediator.InvalidMessageException"/> if request does not implement <see cref="global::Mediator.IStreamRequest{TResponse}"/>.
        /// Throws <see cref="global::Mediator.MissingMessageHandlerException"/> if no handler is registered.
        /// </summary>
        /// <param name="request">Incoming message</param>
        /// <param name="cancellationToken">Cancellation token</param>
        /// <returns>Async enumerable</returns>
        public global::System.Collections.Generic.IAsyncEnumerable<TResponse> CreateStream<TResponse>(
            global::Mediator.IStreamRequest<TResponse> request,
            global::System.Threading.CancellationToken cancellationToken = default
        )
        {
            switch (request)
            {
                case global::TestCode.StreamRequest r:
                {
                    var task = CreateStream(r, cancellationToken);
                    return global::System.Runtime.CompilerServices.Unsafe.As<global::System.Collections.Generic.IAsyncEnumerable<global::TestCode.Response>, global::System.Collections.Generic.IAsyncEnumerable<TResponse>>(ref task);
                }
                default:
                {
                    ThrowInvalidStreamRequest(request, nameof(request));
                    return default!;
                }
            }
        }

        /// <summary>
        /// Send command.
        /// Throws <see cref="global::System.ArgumentNullException"/> if message is null.
        /// Throws <see cref="global::Mediator.InvalidMessageException"/> if command does not implement <see cref="global::Mediator.ICommand{TResponse}"/>.
        /// Throws <see cref="global::Mediator.MissingMessageHandlerException"/> if no handler is registered.
        /// </summary>
        /// <param name="command">Incoming command</param>
        /// <param name="cancellationToken">Cancellation token</param>
        /// <returns>Awaitable task</returns>
        public global::System.Threading.Tasks.ValueTask<TResponse> Send<TResponse>(
            global::Mediator.ICommand<TResponse> command,
            global::System.Threading.CancellationToken cancellationToken = default
        )
        {
            ThrowInvalidCommand(command, nameof(command));
            return default;
        }

        private async global::System.Threading.Tasks.ValueTask<TResponse> SendAsync<TResponse>(
            global::Mediator.ICommand<TResponse> command,
            global::System.Threading.CancellationToken cancellationToken = default
        )
        {
            ThrowInvalidCommand(command, nameof(command));
            return default!;
        }

        /// <summary>
        /// Create stream for command.
        /// Throws <see cref="global::System.ArgumentNullException"/> if message is null.
        /// Throws <see cref="global::Mediator.InvalidMessageException"/> if command does not implement <see cref="global::Mediator.IStreamCommand{TResponse}"/>.
        /// Throws <see cref="global::Mediator.MissingMessageHandlerException"/> if no handler is registered.
        /// </summary>
        /// <param name="command">Incoming message</param>
        /// <param name="cancellationToken">Cancellation token</param>
        /// <returns>Async enumerable</returns>
        public global::System.Collections.Generic.IAsyncEnumerable<TResponse> CreateStream<TResponse>(
            global::Mediator.IStreamCommand<TResponse> command,
            global::System.Threading.CancellationToken cancellationToken = default
        )
        {
            ThrowInvalidStreamCommand(command, nameof(command));
            return default!;
        }

        /// <summary>
        /// Send query.
        /// Throws <see cref="global::System.ArgumentNullException"/> if message is null.
        /// Throws <see cref="global::Mediator.InvalidMessageException"/> if query does not implement <see cref="global::Mediator.IQuery{TResponse}"/>.
        /// Throws <see cref="global::Mediator.MissingMessageHandlerException"/> if no handler is registered.
        /// </summary>
        /// <param name="query">Incoming query</param>
        /// <param name="cancellationToken">Cancellation token</param>
        /// <returns>Awaitable task</returns>
        public global::System.Threading.Tasks.ValueTask<TResponse> Send<TResponse>(
            global::Mediator.IQuery<TResponse> query,
            global::System.Threading.CancellationToken cancellationToken = default
        )
        {
            ThrowInvalidQuery(query, nameof(query));
            return default;
        }

        private async global::System.Threading.Tasks.ValueTask<TResponse> SendAsync<TResponse>(
            global::Mediator.IQuery<TResponse> query,
            global::System.Threading.CancellationToken cancellationToken = default
        )
        {
            ThrowInvalidQuery(query, nameof(query));
            return default!;
        }

        /// <summary>
        /// Create stream for query.
        /// Throws <see cref="global::System.ArgumentNullException"/> if message is null.
        /// Throws <see cref="global::Mediator.InvalidMessageException"/> if query does not implement <see cref="global::Mediator.IStreamQuery{TResponse}"/>.
        /// Throws <see cref="global::Mediator.MissingMessageHandlerException"/> if no handler is registered.
        /// </summary>
        /// <param name="query">Incoming message</param>
        /// <param name="cancellationToken">Cancellation token</param>
        /// <returns>Async enumerable</returns>
        public global::System.Collections.Generic.IAsyncEnumerable<TResponse> CreateStream<TResponse>(
            global::Mediator.IStreamQuery<TResponse> query,
            global::System.Threading.CancellationToken cancellationToken = default
        )
        {
            ThrowInvalidStreamQuery(query, nameof(query));
            return default!;
        }

        /// <summary>
        /// Send message.
        /// Throws <see cref="global::System.ArgumentNullException"/> if message is null.
        /// Throws <see cref="global::Mediator.InvalidMessageException"/> if message does not implement <see cref="global::Mediator.IMessage"/>.
        /// Throws <see cref="global::Mediator.MissingMessageHandlerException"/> if no handler is registered.
        /// </summary>
        /// <param name="message">Incoming message</param>
        /// <param name="cancellationToken">Cancellation token</param>
        /// <returns>Awaitable task</returns>
        public async global::System.Threading.Tasks.ValueTask<object?> Send(
            object message,
            global::System.Threading.CancellationToken cancellationToken = default
        )
        {
            switch (message)
            {
                case global::Mediator.IBaseRequest request:
                    switch (request)
                    {
                        case global::TestCode.Request r: return await Send(r, cancellationToken);
                        default:
                        {
                            ThrowInvalidRequest(request, nameof(request));
                            return default;
                        }
                    }
                case global::Mediator.IBaseCommand command:
                    switch (command)
                    {
                        default:
                        {
                            ThrowInvalidCommand(command, nameof(command));
                            return default;
                        }
                    }
                case global::Mediator.IBaseQuery query:
                    switch (query)
                    {
                        default:
                        {
                            ThrowInvalidQuery(query, nameof(query));
                            return default;
                        }
                    }
                default:
                    ThrowInvalidMessage(message, nameof(message));
                    return default!;
            }
        }

        /// <summary>
        /// Create stream.
        /// Throws <see cref="global::System.ArgumentNullException"/> if message is null.
        /// Throws <see cref="global::Mediator.InvalidMessageException"/> if message does not implement <see cref="global::Mediator.IStreamMessage"/>.
        /// Throws <see cref="global::Mediator.MissingMessageHandlerException"/> if no handler is registered.
        /// </summary>
        /// <param name="message">Incoming message</param>
        /// <param name="cancellationToken">Cancellation token</param>
        /// <returns>Async enumerable</returns>
        public global::System.Collections.Generic.IAsyncEnumerable<object?> CreateStream(
            object message,
            global::System.Threading.CancellationToken cancellationToken = default
        )
        {
            switch (message)
            {
                case global::Mediator.IBaseStreamRequest request:
                    switch (request)
                    {
                        case global::TestCode.StreamRequest m:
                        {
                            var value = CreateStream(m, cancellationToken);
                            return AsyncWrapper(value);
                        }
                        default:
                        {
                            ThrowInvalidStreamMessage(message, nameof(message));
                            return default!;
                        }
                    }
                case global::Mediator.IBaseStreamCommand command:
                    switch (command)
                    {
                        default:
                        {
                            ThrowInvalidStreamMessage(message, nameof(message));
                            return default!;
                        }
                    }
                case global::Mediator.IBaseStreamQuery query:
                    switch (query)
                    {
                        default:
                        {
                            ThrowInvalidStreamMessage(message, nameof(message));
                            return default!;
                        }
                    }
                default:
                    ThrowInvalidStreamMessage(message, nameof(message));
                    return default!;
            }

            static async global::System.Collections.Generic.IAsyncEnumerable<object?> AsyncWrapper<T>(global::System.Collections.Generic.IAsyncEnumerable<T> wrapped, [global::System.Runtime.CompilerServices.EnumeratorCancellation] global::System.Threading.CancellationToken cancellationToken = default) where T : struct
            {
                await foreach (var value in global::System.Threading.Tasks.TaskAsyncEnumerableExtensions.WithCancellation(wrapped, cancellationToken))
                {
                    yield return value;
                }
            }
        }

        /// <summary>
        /// Publish notification.
        /// Throws <see cref="global::System.ArgumentNullException"/> if message is null.
        /// Throws <see cref="global::Mediator.InvalidMessageException"/> if notification does not implement <see cref="global::Mediator.INotification"/>.
        /// Throws <see cref="global::System.AggregateException"/> if handlers throw exception(s).
        /// Drops messages
        /// </summary>
        /// <param name="notification">Incoming notification</param>
        /// <param name="cancellationToken">Cancellation token</param>
        /// <returns>Awaitable task</returns>
        public global::System.Threading.Tasks.ValueTask Publish(
            object notification,
            global::System.Threading.CancellationToken cancellationToken = default
        )
        {
            switch (notification)
            {
                case global::TestCode.PingNotification n: return Publish(n, cancellationToken);
                default:
                {
                    ThrowInvalidNotification(notification, nameof(notification));
                    return default;
                }
            }
        }

        /// <summary>
        /// Send a notification of type global::TestCode.PingNotification.
        /// Throws <see cref="global::System.ArgumentNullException"/> if message is null.
        /// Throws <see cref="global::System.AggregateException"/> if handlers throw exception(s).
        /// </summary>
        /// <param name="notification">Incoming message</param>
        /// <param name="cancellationToken">Cancellation token</param>
        /// <returns>Awaitable task</returns>
        public global::System.Threading.Tasks.ValueTask Publish(
            global::TestCode.PingNotification notification,
            global::System.Threading.CancellationToken cancellationToken = default
        )
        {
            ThrowIfNull(notification, nameof(notification));

            var wrapperObj = Services.GetService(typeof(global::TestCode.PingNotification));
            var wrapper = wrapperObj as global::Mediator.Internals.NotificationHandlerWrapper<global::TestCode.PingNotification>;
            if (wrapper == null)
                ThrowMissingHandler(notification);
            return wrapper!.Handle(this, notification, cancellationToken);
        }

        /// <summary>
        /// Publish notification.
        /// Throws <see cref="global::System.ArgumentNullException"/> if message is null.
        /// Throws <see cref="global::Mediator.InvalidMessageException"/> if notification does not implement <see cref="global::Mediator.INotification"/>.
        /// Throws <see cref="global::System.AggregateException"/> if handlers throw exception(s).
        /// </summary>
        /// <param name="notification">Incoming notification</param>
        /// <param name="cancellationToken">Cancellation token</param>
        /// <returns>Awaitable task</returns>
        public global::System.Threading.Tasks.ValueTask Publish<TNotification>(
            TNotification notification,
            global::System.Threading.CancellationToken cancellationToken = default
        )
            where TNotification : global::Mediator.INotification
        {
            switch (notification)
            {
                case global::TestCode.PingNotification n: return Publish(n, cancellationToken);
                default:
                {
                    ThrowInvalidNotification(notification, nameof(notification));
                    return default;
                }
            }
        }

#if NETSTANDARD2_1_OR_GREATER
        [global::System.Diagnostics.CodeAnalysis.DoesNotReturn]
#endif
        private static void ThrowMissingHandler(object msg) =>
            throw new global::Mediator.MissingMessageHandlerException(msg);

#if NETSTANDARD2_1_OR_GREATER
        [global::System.Diagnostics.CodeAnalysis.DoesNotReturn]
#endif
        private static void ThrowInvalidMessage<T>(T? msg, string? paramName = null)
        {
            if (msg == null)
                ThrowArgumentNull(paramName);
            else if (!(msg is global::Mediator.IMessage))
                ThrowInvalidMessage(msg);
            else
                ThrowMissingHandler(msg);
        }

#if NETSTANDARD2_1_OR_GREATER
        [global::System.Diagnostics.CodeAnalysis.DoesNotReturn]
#endif
        private static void ThrowInvalidRequest<T>(T? msg, string? paramName = null)
        {
            if (msg == null)
                ThrowArgumentNull(paramName);
            else if (!(msg is global::Mediator.IBaseRequest))
                ThrowInvalidMessage(msg);
            else
                ThrowMissingHandler(msg);
        }

#if NETSTANDARD2_1_OR_GREATER
        [global::System.Diagnostics.CodeAnalysis.DoesNotReturn]
#endif
        private static void ThrowInvalidCommand<T>(T? msg, string? paramName = null)
        {
            if (msg == null)
                ThrowArgumentNull(paramName);
            else if (!(msg is global::Mediator.IBaseCommand))
                ThrowInvalidMessage(msg);
            else
                ThrowMissingHandler(msg);
        }

#if NETSTANDARD2_1_OR_GREATER
        [global::System.Diagnostics.CodeAnalysis.DoesNotReturn]
#endif
        private static void ThrowInvalidQuery<T>(T? msg, string? paramName = null)
        {
            if (msg == null)
                ThrowArgumentNull(paramName);
            else if (!(msg is global::Mediator.IBaseQuery))
                ThrowInvalidMessage(msg);
            else
                ThrowMissingHandler(msg);
        }

#if NETSTANDARD2_1_OR_GREATER
        [global::System.Diagnostics.CodeAnalysis.DoesNotReturn]
#endif
        private static void ThrowInvalidStreamMessage<T>(T? msg, string? paramName = null)
        {
            if (msg == null)
                ThrowArgumentNull(paramName);
            else if (!(msg is global::Mediator.IStreamMessage))
                ThrowInvalidMessage(msg);
            else
                ThrowMissingHandler(msg);
        }

#if NETSTANDARD2_1_OR_GREATER
        [global::System.Diagnostics.CodeAnalysis.DoesNotReturn]
#endif
        private static void ThrowInvalidStreamRequest<T>(T? msg, string? paramName = null)
        {
            if (msg == null)
                ThrowArgumentNull(paramName);
            else if (!(msg is global::Mediator.IBaseStreamRequest))
                ThrowInvalidMessage(msg);
            else
                ThrowMissingHandler(msg);
        }

#if NETSTANDARD2_1_OR_GREATER
        [global::System.Diagnostics.CodeAnalysis.DoesNotReturn]
#endif
        private static void ThrowInvalidStreamCommand<T>(T? msg, string? paramName = null)
        {
            if (msg == null)
                ThrowArgumentNull(paramName);
            else if (!(msg is global::Mediator.IBaseStreamCommand))
                ThrowInvalidMessage(msg);
            else
                ThrowMissingHandler(msg);
        }

#if NETSTANDARD2_1_OR_GREATER
        [global::System.Diagnostics.CodeAnalysis.DoesNotReturn]
#endif
        private static void ThrowInvalidStreamQuery<T>(T? msg, string? paramName = null)
        {
            if (msg == null)
                ThrowArgumentNull(paramName);
            else if (!(msg is global::Mediator.IBaseStreamQuery))
                ThrowInvalidMessage(msg);
            else
                ThrowMissingHandler(msg);
        }

#if NETSTANDARD2_1_OR_GREATER
        [global::System.Diagnostics.CodeAnalysis.DoesNotReturn]
#endif
        private static void ThrowArgumentNull(string? paramName) =>
            throw new global::System.ArgumentNullException(paramName);

#if NETSTANDARD2_1_OR_GREATER
        [global::System.Diagnostics.CodeAnalysis.DoesNotReturn]
#endif
        private static void ThrowInvalidMessage<T>(T msg) =>
            throw new global::Mediator.InvalidMessageException(msg);

        private static void ThrowIfNull<T>(T? argument, string paramName)
        {
            if (argument == null)
                ThrowArgumentNull(paramName);
        }

        private static void ThrowInvalidNotification<T>(T? argument, string paramName)
        {
            if (argument == null)
                ThrowArgumentNull(paramName);
            else if (!(argument is global::Mediator.INotification))
                ThrowInvalidMessage(argument);
        }

#if NETSTANDARD2_1_OR_GREATER
        [global::System.Diagnostics.CodeAnalysis.DoesNotReturn]
#endif
        private static void ThrowAggregateException(global::System.Collections.Generic.List<global::System.Exception> exceptions) =>
            throw new global::System.AggregateException(exceptions);

        private static void MaybeThrowAggregateException(global::System.Collections.Generic.List<global::System.Exception>? exceptions)
        {
            if (exceptions != null)
            {
                ThrowAggregateException(exceptions);
            }
        }
    }
}
