// <auto-generated>
//     Generated by the Mediator source generator.
// </auto-generated>

namespace Mediator
{
    /// <summary>
    /// Provide options for the Mediator source generator.
    /// </summary>
    [global::System.AttributeUsage(global::System.AttributeTargets.Assembly, AllowMultiple = false)]
    [global::System.CodeDom.Compiler.GeneratedCode("Mediator.SourceGenerator", "1.0.0.0")]
    public sealed class MediatorOptionsAttribute : global::System.Attribute
    {
        private readonly string _namespace;

        /// <summary>
        /// Provide options for the Mediator source generator.
        /// </summary>
        public MediatorOptionsAttribute(string mediatorNamespace = "Mediator")
        {
            _namespace = mediatorNamespace;
        }
    }
}
